// src/pages/group-create/GroupCreatePage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { z } from 'zod'
import { toast } from 'vue-sonner'
import TopBar from '@/shared/components/TopBar.vue'
import { Button } from '@/shared/components/ui/button'
import { Input } from '@/shared/components/ui/input'
import { Label } from '@/shared/components/ui/label'
import { Textarea } from '@/shared/components/ui/textarea'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shared/components/ui/tabs'
import { Spinner } from '@/shared/components/ui/spinner'
import { useGroupStore } from '@/features/group/stores/group'
import { routes } from '@/app/router/routes/index.ts'
import { Users, Hash } from 'lucide-vue-next'

const { t } = useI18n()
const router = useRouter()
const groupStore = useGroupStore()

interface CreateFormValues {
    name: string
    description: string
}

interface JoinFormValues {
    code: string
}

const createLoading = ref(false)
const joinLoading = ref(false)

const createFormSchema = toTypedSchema(z.object({
    name: z.string().trim().min(1, t('group.nameRequired')).max(50, t('group.nameTooLong')),
    description: z.string()
}))

const joinFormSchema = toTypedSchema(z.object({
    code: z.string().trim().min(1, t('group.codeRequired'))
}))

const createForm = useForm<CreateFormValues>({
    validationSchema: createFormSchema,
    initialValues: {
        name: '',
        description: ''
    }
})

const joinForm = useForm<JoinFormValues>({
    validationSchema: joinFormSchema,
    initialValues: {
        code: ''
    }
})

const [createName, createNameAttrs] = createForm.defineField('name')
const [createDescription, createDescriptionAttrs] = createForm.defineField('description')
const [joinCode, joinCodeAttrs] = joinForm.defineField('code')

const createNameError = computed(() => createForm.errors.value.name ?? '')
const joinCodeError = computed(() => joinForm.errors.value.code ?? '')
const createNameLength = computed(() => String(createName.value ?? '').length)

const handleCreate = createForm.handleSubmit(async (values) => {
    createLoading.value = true

    try {
        const groupId = await groupStore.createGroup(
            values.name,
            values.description.trim() || undefined
        )

        const newGroup = groupStore.groups.find(g => g.id === groupId)
        const invCode = newGroup?.invitation_code ?? ''

        if (invCode) {
            toast.success(t('group.createSuccess', { code: invCode }))
        } else {
            toast.success(t('group.createSuccessNoCode'))
        }

        router.push({ name: routes.groupSettings.name, params: { id: groupId } })
    } catch (err) {
        const message = err instanceof Error ? err.message : t('common.error')
        toast.error(message)
    } finally {
        createLoading.value = false
    }
})

const handleJoin = joinForm.handleSubmit(async (values) => {
    joinLoading.value = true

    try {
        await groupStore.joinGroupWithCode(values.code.toUpperCase())
        toast.success(t('group.joinSuccess'))
        router.push({ name: routes.dashboard.name })
    } catch (err) {
        const message = err instanceof Error ? err.message : t('common.error')
        toast.error(message)
    } finally {
        joinLoading.value = false
    }
})
</script>

<template>
    <div class="min-h-screen bg-background glass-page-bg">
        <TopBar
            :title="t('group.createOrJoin')"
            :show-back-button="true"
            @back="router.back()"
        />

        <main class="px-4 pb-28 pt-6">
            <Tabs default-value="create" class="w-full">
                <TabsList class="grid w-full grid-cols-2 mb-6 glass-light rounded-full p-1">
                    <TabsTrigger
                        value="create"
                        class="rounded-full data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm transition-all duration-200"
                    >
                        {{ t('group.createGroup') }}
                    </TabsTrigger>
                    <TabsTrigger
                        value="join"
                        class="rounded-full data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm transition-all duration-200"
                    >
                        {{ t('group.joinGroup') }}
                    </TabsTrigger>
                </TabsList>

                <TabsContent value="create">
                    <div class="glass-elevated rounded-2xl p-6">
                        <form class="space-y-5" @submit="handleCreate">
                            <div class="flex justify-center mb-2">
                                <div class="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10">
                                    <Users class="h-8 w-8 text-brand-primary" />
                                </div>
                            </div>

                            <div class="text-center space-y-1 mb-4">
                                <h2 class="text-lg font-semibold text-foreground">
                                    {{ t('group.createGroupTitle') }}
                                </h2>
                                <p class="text-sm text-muted-foreground">
                                    {{ t('group.createGroupDesc') }}
                                </p>
                            </div>

                            <div class="space-y-2">
                                <Label for="group-name">
                                    {{ t('group.groupName') }}
                                    <span class="text-destructive">*</span>
                                </Label>
                                <Input
                                    id="group-name"
                                    v-model="createName"
                                    v-bind="createNameAttrs"
                                    :placeholder="t('group.groupNamePlaceholder')"
                                    maxlength="50"
                                    :class="createNameError ? 'border-destructive' : ''"
                                />
                                <div class="flex justify-between items-center">
                                    <p v-if="createNameError" class="text-xs text-destructive">
                                        {{ createNameError }}
                                    </p>
                                    <span v-else class="flex-1" />
                                    <span class="text-xs text-muted-foreground">
                                        {{ createNameLength }}/50
                                    </span>
                                </div>
                            </div>

                            <div class="space-y-2">
                                <Label for="group-description">
                                    {{ t('group.groupDescription') }}
                                    <span class="text-xs text-muted-foreground ml-1">
                                        ({{ t('common.optional') }})
                                    </span>
                                </Label>
                                <Textarea
                                    id="group-description"
                                    v-model="createDescription"
                                    v-bind="createDescriptionAttrs"
                                    :placeholder="t('group.groupDescriptionPlaceholder')"
                                    rows="3"
                                    class="resize-none"
                                />
                            </div>

                            <Button
                                type="submit"
                                class="w-full bg-brand-primary hover:bg-brand-primary/90 text-primary-foreground"
                                :disabled="createLoading"
                            >
                                <Spinner v-if="createLoading" class="mr-2 h-4 w-4" />
                                {{ t('group.createGroup') }}
                            </Button>
                        </form>
                    </div>
                </TabsContent>

                <TabsContent value="join">
                    <div class="glass-elevated rounded-2xl p-6">
                        <form class="space-y-5" @submit="handleJoin">
                            <div class="flex justify-center mb-2">
                                <div class="flex h-16 w-16 items-center justify-center rounded-2xl glass-light">
                                    <Hash class="h-8 w-8 text-emerald-600 dark:text-emerald-400" />
                                </div>
                            </div>

                            <div class="text-center space-y-1 mb-4">
                                <h2 class="text-lg font-semibold text-foreground">
                                    {{ t('group.joinGroupTitle') }}
                                </h2>
                                <p class="text-sm text-muted-foreground">
                                    {{ t('group.joinGroupDesc') }}
                                </p>
                            </div>

                            <div class="space-y-2">
                                <Label for="join-code">
                                    {{ t('group.invitationCode') }}
                                    <span class="text-destructive">*</span>
                                </Label>
                                <Input
                                    id="join-code"
                                    v-model="joinCode"
                                    v-bind="joinCodeAttrs"
                                    :placeholder="t('group.invitationCodePlaceholder')"
                                    class="font-mono text-2xl tracking-[0.5em] text-center uppercase h-14 border-2"
                                    :class="joinCodeError ? 'border-destructive' : ''"
                                    autocomplete="off"
                                    autocorrect="off"
                                    autocapitalize="characters"
                                    spellcheck="false"
                                />
                                <p v-if="joinCodeError" class="text-xs text-destructive">
                                    {{ joinCodeError }}
                                </p>
                                <p v-else class="text-xs text-muted-foreground">
                                    {{ t('group.invitationCodeHint') }}
                                </p>
                            </div>

                            <Button
                                type="submit"
                                class="w-full bg-brand-primary hover:bg-brand-primary/90 text-primary-foreground"
                                :disabled="joinLoading"
                            >
                                <Spinner v-if="joinLoading" class="mr-2 h-4 w-4" />
                                {{ t('group.joinGroup') }}
                            </Button>
                        </form>
                    </div>
                </TabsContent>
            </Tabs>
        </main>
    </div>
</template>

// src/pages/group-create/GroupCreatePage.tsx
import { useState } from 'react'
import type { SyntheticEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from '@tanstack/react-router'
import { Hash, Users } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useCreateGroup, useJoinGroup } from '@/features/group/api/useGroupMutations'

export default function GroupCreatePage() {
    const { t } = useTranslation()
    const navigate = useNavigate()
    const createGroup = useCreateGroup()
    const joinGroup = useJoinGroup()
    const [name, setName] = useState('')
    const [description, setDescription] = useState('')
    const [code, setCode] = useState('')
    const [createError, setCreateError] = useState('')
    const [joinError, setJoinError] = useState('')

    const handleCreate = async (event: SyntheticEvent<HTMLFormElement>) => {
        event.preventDefault()
        const trimmedName = name.trim()
        const trimmedDescription = description.trim()

        if (!trimmedName) {
            setCreateError(t('group.nameRequired'))
            return
        }
        if (trimmedName.length > 50) {
            setCreateError(t('group.nameTooLong'))
            return
        }

        setCreateError('')
        try {
            const groupId = await createGroup.mutateAsync({
                name: trimmedName,
                description: trimmedDescription || undefined
            })
            toast.success(t('group.createSuccessNoCode'))
            void navigate({ to: '/groups/$id', params: { id: groupId } })
        } catch (error) {
            toast.error(error instanceof Error ? error.message : t('group.createError'))
        }
    }

    const handleJoin = async (event: SyntheticEvent<HTMLFormElement>) => {
        event.preventDefault()
        const invitationCode = code.trim().toUpperCase()

        if (!invitationCode) {
            setJoinError(t('group.codeRequired'))
            return
        }

        setJoinError('')
        try {
            await joinGroup.mutateAsync(invitationCode)
            toast.success(t('group.joinSuccess'))
            void navigate({ to: '/dashboard' })
        } catch (error) {
            toast.error(error instanceof Error ? error.message : t('group.joinError'))
        }
    }

    return (
        <main className="px-4 pt-6 pb-28">
            <Tabs defaultValue="create" className="w-full">
                <TabsList className="glass-light mb-6 grid w-full grid-cols-2 rounded-full p-1">
                    <TabsTrigger
                        value="create"
                        className="rounded-full transition-all duration-200 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm"
                    >
                        {t('group.createGroup')}
                    </TabsTrigger>
                    <TabsTrigger
                        value="join"
                        className="rounded-full transition-all duration-200 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground data-[state=active]:shadow-sm"
                    >
                        {t('group.joinGroup')}
                    </TabsTrigger>
                </TabsList>

                <TabsContent value="create">
                    <section className="glass-elevated rounded-2xl p-6">
                        <form className="space-y-5" onSubmit={handleCreate}>
                            <div className="mb-2 flex justify-center">
                                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10">
                                    <Users className="h-8 w-8 text-brand-primary" />
                                </div>
                            </div>

                            <div className="mb-4 space-y-1 text-center">
                                <h2 className="text-lg font-semibold text-foreground">{t('group.createGroupTitle')}</h2>
                                <p className="text-sm text-muted-foreground">{t('group.createGroupDesc')}</p>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="group-name">
                                    {t('group.groupName')}
                                    <span className="text-destructive">*</span>
                                </Label>
                                <Input
                                    id="group-name"
                                    value={name}
                                    maxLength={50}
                                    aria-invalid={!!createError}
                                    placeholder={t('group.groupNamePlaceholder')}
                                    onChange={(event) => {
                                        setName(event.target.value)
                                        if (createError) setCreateError('')
                                    }}
                                />
                                <div className="flex items-center justify-between">
                                    {createError ? (
                                        <p className="text-xs text-destructive">{createError}</p>
                                    ) : (
                                        <span />
                                    )}
                                    <span className="text-xs text-muted-foreground">{name.length}/50</span>
                                </div>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="group-description">
                                    {t('group.groupDescription')}
                                    <span className="ml-1 text-xs text-muted-foreground">({t('common.optional')})</span>
                                </Label>
                                <textarea
                                    id="group-description"
                                    value={description}
                                    rows={3}
                                    className="min-h-20 w-full resize-none rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-xs outline-none transition-[color,box-shadow] placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50"
                                    placeholder={t('group.groupDescriptionPlaceholder')}
                                    onChange={(event) => setDescription(event.target.value)}
                                />
                            </div>

                            <Button
                                type="submit"
                                className="press-feedback w-full bg-brand-primary text-primary-foreground hover:bg-brand-primary/90"
                                disabled={createGroup.isPending}
                            >
                                {createGroup.isPending ? t('common.processing') : t('group.createGroup')}
                            </Button>
                        </form>
                    </section>
                </TabsContent>

                <TabsContent value="join">
                    <section className="glass-elevated rounded-2xl p-6">
                        <form className="space-y-5" onSubmit={handleJoin}>
                            <div className="mb-2 flex justify-center">
                                <div className="glass-light flex h-16 w-16 items-center justify-center rounded-2xl">
                                    <Hash className="h-8 w-8 text-emerald-600 dark:text-emerald-400" />
                                </div>
                            </div>

                            <div className="mb-4 space-y-1 text-center">
                                <h2 className="text-lg font-semibold text-foreground">{t('group.joinGroupTitle')}</h2>
                                <p className="text-sm text-muted-foreground">{t('group.joinGroupDesc')}</p>
                            </div>

                            <div className="space-y-2">
                                <Label htmlFor="join-code">
                                    {t('group.invitationCode')}
                                    <span className="text-destructive">*</span>
                                </Label>
                                <Input
                                    id="join-code"
                                    value={code}
                                    aria-invalid={!!joinError}
                                    autoComplete="off"
                                    autoCorrect="off"
                                    autoCapitalize="characters"
                                    spellCheck={false}
                                    className="h-14 border-2 text-center font-mono text-2xl tracking-[0.5em] uppercase"
                                    placeholder={t('group.invitationCodePlaceholder')}
                                    onChange={(event) => {
                                        setCode(event.target.value)
                                        if (joinError) setJoinError('')
                                    }}
                                />
                                {joinError ? (
                                    <p className="text-xs text-destructive">{joinError}</p>
                                ) : (
                                    <p className="text-xs text-muted-foreground">{t('group.invitationCodeHint')}</p>
                                )}
                            </div>

                            <Button
                                type="submit"
                                className="press-feedback w-full bg-brand-primary text-primary-foreground hover:bg-brand-primary/90"
                                disabled={joinGroup.isPending}
                            >
                                {joinGroup.isPending ? t('common.processing') : t('group.joinGroup')}
                            </Button>
                        </form>
                    </section>
                </TabsContent>
            </Tabs>
        </main>
    )
}
