// src/pages/expenses/ExpensesPage.vue
<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue'
import { useStorage, refDebounced } from '@vueuse/core'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { storeToRefs } from 'pinia'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shared/components/ui/tabs'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/shared/components/ui/dialog'
import { Input } from '@/shared/components/ui/input'
import { Button } from '@/shared/components/ui/button'
import { Label } from '@/shared/components/ui/label'
import { Calendar } from '@/shared/components/ui/calendar'
import { Popover, PopoverContent, PopoverTrigger } from '@/shared/components/ui/popover'
import { Slider } from '@/shared/components/ui/slider'
import { type DateValue } from '@internationalized/date'
import TopBar from '@/shared/components/TopBar.vue'
import ExpenseGroup from '@/features/expense/components/ExpenseGroup.vue'
import { useExpenseStore } from '@/shared/stores'
import { useGroupStore } from '@/features/group/stores/group'
import { usePullToRefresh } from '@/shared/composables/usePullToRefresh'
import { useCategories, CategoryUtils } from '@/features/expense/composables/useCategories'
import { formatAmount } from '@/shared/utils'
import type { Expense } from '@/features/expense/stores/expense'
import type { DisplayExpense } from '@/entities/expense/types'
import { toast } from 'vue-sonner'
import { User, Users, Calendar as CalendarIcon, Search, SlidersHorizontal, Plus, RefreshCw, Wallet, HandCoins } from 'lucide-vue-next'
import RecurringExpenseDrawer from '@/features/expense/components/RecurringExpenseDrawer.vue'
import RecurringExpenseList from '@/features/expense/components/RecurringExpenseList.vue'
import type { RecurringExpense } from '@/entities/expense/types'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const { categories } = useCategories()
const expenseStore = useExpenseStore()
const groupStore = useGroupStore()

const {
    personalExpenses,
    allMyExpenses,
    groupExpenses
} = storeToRefs(expenseStore)

const isInGroup = computed(() => groupStore.isInAnyGroup)

// 群組 ID → 名稱映射（供個人 tab 顯示群組 badge 使用）
const groupNameMap = computed(() => {
    const map = new Map<string, string>()
    for (const g of groupStore.groups) {
        map.set(g.id, g.name)
    }
    return map
})

// 持久化 Tab 選擇（localStorage），URL query 可覆蓋
const savedTab = useStorage<string>('expenses-active-tab', 'personal')
const urlTab = route.query.tab as string | undefined
const resolvedTab = urlTab || savedTab.value || 'personal'
const activeTab = ref<string>(resolvedTab === 'group' && !groupStore.isInAnyGroup ? 'personal' : resolvedTab)

const isPreloading = computed(() => expenseStore.preloadStatus === 'loading' || expenseStore.preloadStatus === 'idle')

// 個人 Tab 的支出類型子篩選：全部 / 個人 / 欠款
type ExpenseTypeFilter = 'all' | 'personal' | 'debt'
const expenseTypeFilter = ref<ExpenseTypeFilter>('all')

// 搜尋查詢（300ms debounce 減少每次按鍵觸發的計算）
const searchQuery = ref('')
const debouncedSearch = refDebounced(searchQuery, 300)

// 篩選 Dialog 狀態
const isFilterDialogOpen = ref(false)

// 日期選擇狀態
const startDateValue = ref<DateValue>()
const endDateValue = ref<DateValue>()

// 篩選條件
const filters = ref({
    startDate: null as string | null,
    endDate: null as string | null,
    categories: [] as string[],
    minAmount: '',
    maxAmount: ''
})

// 滑動條數值
const sliderValues = ref([0, 3000])
const maxPossibleAmount = 10000

// 是否有啟用的篩選條件
const hasActiveFilters = computed(() => {
    return filters.value.categories.length > 0
        || filters.value.startDate !== null
        || filters.value.endDate !== null
        || filters.value.minAmount !== ''
        || filters.value.maxAmount !== ''
})

// 防止 slider ↔ input 循環觸發的 flag
const syncingFromSlider = ref(false)

// 監聽滑動條變化並更新輸入框
watch(sliderValues, (newValues) => {
    syncingFromSlider.value = true
    filters.value.minAmount = (newValues[0] ?? 0).toString()
    filters.value.maxAmount = (newValues[1] ?? maxPossibleAmount).toString()
    nextTick(() => { syncingFromSlider.value = false })
})

// 監聽輸入框變化並更新滑動條（slider 驅動時跳過）
watch(() => [filters.value.minAmount, filters.value.maxAmount], ([min, max]) => {
    if (syncingFromSlider.value) return
    sliderValues.value = [
        min ? parseFloat(min) : 0,
        max ? parseFloat(max) : maxPossibleAmount
    ]
})

// 監聽 route query 變化
watch(() => route.query.tab, (newTab) => {
    if (newTab && (newTab === 'personal' || newTab === 'group')) {
        activeTab.value = newTab
    }
})

// 監聽 tab 變化，更新 URL 和持久化儲存
watch(activeTab, (newTab) => {
    savedTab.value = newTab
    router.replace({ query: { ...route.query, tab: newTab } })
})

// 懶計算：只取當前 tab 的支出來源
// 個人 tab 顯示使用者所有消費（含群組），群組 tab 顯示活躍群組消費
const activeExpenses = computed(() => {
    if (activeTab.value === 'group') return groupExpenses.value

    const expenses = allMyExpenses.value
    if (expenseTypeFilter.value === 'personal') {
        return expenses.filter(e => e.group_id === null)
    }
    if (expenseTypeFilter.value === 'debt') {
        return expenses.filter(e => e.group_id !== null)
    }
    return expenses
})

// 快取 DisplayExpense 轉換（避免每次 computed 重算時重建所有物件）
const displayExpenseMap = computed(() => {
    const map = new Map<string, DisplayExpense>()
    for (const e of activeExpenses.value) {
        map.set(e.id, {
            id: e.id,
            title: e.title,
            amount: formatAmount(e.amount),
            numericAmount: e.amount,
            category: e.category,
            icon: CategoryUtils.getIconKey(e.category),
            user: e.user,
            groupId: e.group_id,
            groupName: e.group_id ? (groupNameMap.value.get(e.group_id) ?? null) : null,
            splitMethod: e.split_method,
            isSettled: e.is_settled
        })
    }
    return map
})

// 篩選邏輯（single-pass，使用 debounced 搜尋值）
const applyFilters = (expenses: Expense[]) => {
    const query = debouncedSearch.value?.toLowerCase()
    const startDate = filters.value.startDate?.replace(/\//g, '-')
    const endDate = filters.value.endDate?.replace(/\//g, '-')
    const cats = filters.value.categories
    const min = filters.value.minAmount ? parseFloat(filters.value.minAmount) : null
    const max = filters.value.maxAmount ? parseFloat(filters.value.maxAmount) : null

    return expenses.filter(e =>
        (!query || e.title.toLowerCase().includes(query))
        && (!startDate || e.date >= startDate)
        && (!endDate || e.date <= endDate)
        && (cats.length === 0 || cats.includes(e.category))
        && (min === null || e.amount >= min)
        && (max === null || e.amount <= max)
    )
}

// 篩選後的支出（只計算活躍 tab）
const filteredExpenses = computed(() => applyFilters(activeExpenses.value))

// 按日期分組工具函式
const groupByDate = (expenses: Expense[]): { date: string; expenses: DisplayExpense[] }[] => {
    const groups: Record<string, DisplayExpense[]> = {}

    for (const expense of expenses) {
        const displayDate = expense.date.replace(/-/g, '/')
        if (!groups[displayDate]) {
            groups[displayDate] = []
        }
        const display = displayExpenseMap.value.get(expense.id)
        if (display) {
            groups[displayDate].push(display)
        }
    }

    return Object.entries(groups)
        .map(([date, exps]) => ({ date, expenses: exps }))
        .sort((a, b) => b.date.localeCompare(a.date))
}

// 活躍 tab 的分組結果
const expenseGroups = computed(() => groupByDate(filteredExpenses.value))

// 日期格式化
const formatDate = (dateStr: string) => {
    return dateStr
}

// 日期選擇處理
const handleStartDateSelect = (date: DateValue | undefined) => {
    if (date) {
        filters.value.startDate = `${date.year}/${String(date.month).padStart(2, '0')}/${String(date.day).padStart(2, '0')}`
    }
}

const handleEndDateSelect = (date: DateValue | undefined) => {
    if (date) {
        filters.value.endDate = `${date.year}/${String(date.month).padStart(2, '0')}/${String(date.day).padStart(2, '0')}`
    }
}

// 切換類別選擇
const toggleCategory = (categoryId: string) => {
    const index = filters.value.categories.indexOf(categoryId)
    if (index > -1) {
        filters.value = {
            ...filters.value,
            categories: filters.value.categories.filter((_, i) => i !== index)
        }
    } else {
        filters.value = {
            ...filters.value,
            categories: [...filters.value.categories, categoryId]
        }
    }
}

// 重設篩選
const resetFilters = () => {
    filters.value = {
        startDate: null,
        endDate: null,
        categories: [],
        minAmount: '',
        maxAmount: ''
    }
    startDateValue.value = undefined
    endDateValue.value = undefined
    sliderValues.value = [0, maxPossibleAmount]
    searchQuery.value = ''
}

// 套用篩選
const handleApplyFilters = () => {
    isFilterDialogOpen.value = false
}

// 處理費用項目點擊 → 導航到詳情頁
const handleExpenseClick = (expense: DisplayExpense) => {
    if (expense.id) {
        router.push({ name: 'ExpenseDetail', params: { id: expense.id } })
    }
}

// 定期消費抽屜狀態
const isRecurringDrawerOpen = ref(false)
const editingRecurring = ref<RecurringExpense | null>(null)

function openAddRecurring() {
    editingRecurring.value = null
    isRecurringDrawerOpen.value = true
}

function openEditRecurring(item: RecurringExpense) {
    editingRecurring.value = item
    isRecurringDrawerOpen.value = true
}

// 下拉刷新
usePullToRefresh({
    onRefresh: async () => {
        try {
            expenseStore.preloadStatus = 'loading'
            await expenseStore.fetchExpenses()
            expenseStore.preloadStatus = 'done'
            toast.success(t('common.refreshed'))
        } catch (err) {
            console.error('刷新失敗:', err)
            expenseStore.preloadStatus = 'error'
            toast.error(t('common.refreshFailed'))
        }
    }
})
</script>

<template>
    <div class="min-h-screen bg-background glass-page-bg">
        <TopBar :title="t('nav.expenses')" />

        <!-- 搜尋區域 -->
        <div class="sticky top-[64px] z-40 px-4 py-3 bg-background/80 backdrop-blur-xl">
            <div class="flex gap-2 glass rounded-full p-1.5">
                <!-- 搜尋輸入框 -->
                <div class="flex-1 relative">
                    <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                    <Input
                        v-model="searchQuery"
                        type="text"
                        :placeholder="t('search.searchTransaction')"
                        class="pl-10 pr-4 h-11 border-0 bg-transparent shadow-none focus-visible:ring-0"
                    />
                </div>

                <!-- 篩選按鈕 -->
                <div class="relative">
                    <Button
                        variant="outline"
                        size="icon"
                        class="h-11 w-11 rounded-full press-feedback hover-transition"
                        @click="isFilterDialogOpen = true"
                    >
                        <SlidersHorizontal class="h-5 w-5" />
                    </Button>
                    <span
                        v-if="hasActiveFilters"
                        class="absolute -top-0.5 -right-0.5 h-2.5 w-2.5 bg-red-500 rounded-full"
                    />
                </div>
            </div>
        </div>

        <main class="px-4 pb-28">
            <!-- Tab 切換 -->
            <Tabs v-model="activeTab" class="mt-4">
                <TabsList class="grid w-full grid-cols-3 rounded-full glass-light p-[2px]">
                    <TabsTrigger
                        value="personal"
                        class="flex items-center gap-2 rounded-full data-[state=active]:bg-primary data-[state=active]:text-primary-foreground transition-all duration-200 press-feedback"
                    >
                        <User class="h-4 w-4" />
                        {{ t('expense.personal') }}
                    </TabsTrigger>
                    <TabsTrigger
                        value="group"
                        :disabled="!isInGroup"
                        class="flex items-center gap-2 rounded-full data-[state=active]:bg-primary data-[state=active]:text-primary-foreground transition-all duration-200 press-feedback"
                    >
                        <Users class="h-4 w-4" />
                        {{ t('expense.group') }}
                    </TabsTrigger>
                    <TabsTrigger
                        value="recurring"
                        class="flex items-center gap-2 rounded-full data-[state=active]:bg-primary data-[state=active]:text-primary-foreground transition-all duration-200 press-feedback"
                    >
                        <RefreshCw class="h-4 w-4" />
                        {{ t('recurring.title') }}
                    </TabsTrigger>
                </TabsList>

                <!-- 個人支出列表 -->
                <TabsContent value="personal" class="mt-4">
                    <!-- 支出類型子篩選 -->
                    <div class="flex gap-2 mb-4">
                        <button
                            v-for="filter in ([
                                { value: 'all', label: t('dashboard.filterAll'), icon: null },
                                { value: 'personal', label: t('dashboard.filterPersonal'), icon: Wallet },
                                { value: 'debt', label: t('dashboard.filterDebt'), icon: HandCoins }
                            ] as const)"
                            :key="filter.value"
                            type="button"
                            :class="[
                                'flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-sm font-medium transition-all duration-200 press-feedback',
                                expenseTypeFilter === filter.value
                                    ? 'bg-primary text-primary-foreground shadow-sm'
                                    : 'glass text-muted-foreground hover:text-foreground'
                            ]"
                            @click="expenseTypeFilter = filter.value"
                        >
                            <component
                                v-if="filter.icon"
                                :is="filter.icon"
                                class="h-3.5 w-3.5"
                            />
                            {{ filter.label }}
                        </button>
                    </div>

                    <!-- Skeleton 載入中 -->
                    <div v-if="isPreloading" class="space-y-4">
                        <div v-for="i in 3" :key="i" class="glass rounded-2xl p-4 space-y-3">
                            <div class="h-4 bg-muted rounded w-24 animate-pulse" />
                            <div v-for="j in 2" :key="j" class="flex items-center gap-3">
                                <div class="h-10 w-10 bg-muted rounded-lg animate-pulse" />
                                <div class="flex-1 space-y-1.5">
                                    <div class="h-3.5 bg-muted rounded w-32 animate-pulse" />
                                    <div class="h-3 bg-muted rounded w-20 animate-pulse" />
                                </div>
                                <div class="h-4 bg-muted rounded w-16 animate-pulse" />
                            </div>
                        </div>
                    </div>

                    <!-- 支出列表 -->
                    <div v-else-if="expenseGroups.length > 0" class="space-y-4">
                        <ExpenseGroup
                            v-for="group in expenseGroups"
                            :key="group.date"
                            :date="group.date"
                            :expenses="group.expenses"
                            :show-user="false"
                            @expense-click="handleExpenseClick"
                        />
                    </div>

                    <!-- 空狀態 -->
                    <div v-else-if="!expenseStore.loading" class="text-center py-12">
                        <User class="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" />
                        <p class="text-muted-foreground mb-4">
                            {{ searchQuery || filters.categories.length > 0 ? t('search.noResultsFound') : t('expenses.noPersonalExpenses') }}
                        </p>
                        <Button variant="outline" class="rounded-full gap-2 press-feedback">
                            <Plus class="h-4 w-4" />
                            {{ t('expense.addExpense') }}
                        </Button>
                    </div>
                </TabsContent>

                <!-- 群組支出列表 -->
                <TabsContent value="group" class="mt-4">
                    <!-- Skeleton 載入中 -->
                    <div v-if="isPreloading" class="space-y-4">
                        <div v-for="i in 3" :key="i" class="glass rounded-2xl p-4 space-y-3">
                            <div class="h-4 bg-muted rounded w-24 animate-pulse" />
                            <div v-for="j in 2" :key="j" class="flex items-center gap-3">
                                <div class="h-10 w-10 bg-muted rounded-lg animate-pulse" />
                                <div class="flex-1 space-y-1.5">
                                    <div class="h-3.5 bg-muted rounded w-32 animate-pulse" />
                                    <div class="h-3 bg-muted rounded w-20 animate-pulse" />
                                </div>
                                <div class="h-4 bg-muted rounded w-16 animate-pulse" />
                            </div>
                        </div>
                    </div>

                    <!-- 支出列表 -->
                    <div v-else-if="expenseGroups.length > 0" class="space-y-4">
                        <ExpenseGroup
                            v-for="group in expenseGroups"
                            :key="group.date"
                            :date="group.date"
                            :expenses="group.expenses"
                            :show-user="true"
                            @expense-click="handleExpenseClick"
                        />
                    </div>

                    <!-- 空狀態 -->
                    <div v-else-if="!expenseStore.loading" class="text-center py-12">
                        <Users class="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" />
                        <p class="text-muted-foreground mb-4">
                            {{ searchQuery || filters.categories.length > 0 ? t('search.noResultsFound') : t('expenses.noGroupExpenses') }}
                        </p>
                        <Button variant="outline" class="rounded-full gap-2 press-feedback">
                            <Plus class="h-4 w-4" />
                            {{ t('expense.addExpense') }}
                        </Button>
                    </div>
                </TabsContent>

                <!-- 定期消費 Tab -->
                <TabsContent value="recurring" class="mt-4">
                    <div class="flex justify-end mb-3">
                        <Button
                            size="sm"
                            class="rounded-full gap-2 press-feedback"
                            @click="openAddRecurring"
                        >
                            <Plus class="h-4 w-4" />
                            {{ t('recurring.add') }}
                        </Button>
                    </div>
                    <RecurringExpenseList @edit="openEditRecurring" />
                </TabsContent>
            </Tabs>
        </main>

        <!-- 定期消費抽屜 -->
        <RecurringExpenseDrawer
            v-model:open="isRecurringDrawerOpen"
            :edit-item="editingRecurring"
        />

        <!-- 篩選 Dialog -->
        <Dialog v-model:open="isFilterDialogOpen">
            <DialogContent class="sm:max-w-md bg-card">
                <DialogHeader>
                    <DialogTitle>{{ t('search.filterConditions') }}</DialogTitle>
                    <DialogDescription>
                        {{ t('search.setFilterDesc') }}
                    </DialogDescription>
                </DialogHeader>

                <div class="grid gap-4 py-4">
                    <!-- 日期範圍 -->
                    <div class="space-y-2">
                        <Label>{{ t('search.dateRange') }}</Label>
                        <div class="grid grid-cols-2 gap-2">
                            <div>
                                <Popover>
                                    <PopoverTrigger asChild>
                                        <Button
                                            variant="outline"
                                            class="w-full justify-start text-left font-normal"
                                        >
                                            <CalendarIcon class="mr-2 h-4 w-4" />
                                            {{ filters.startDate ? formatDate(filters.startDate) : t('search.startDate') }}
                                        </Button>
                                    </PopoverTrigger>
                                    <PopoverContent class="w-auto p-0" align="start">
                                        <Calendar v-model="startDateValue" @update:model-value="handleStartDateSelect" />
                                    </PopoverContent>
                                </Popover>
                            </div>
                            <div>
                                <Popover>
                                    <PopoverTrigger asChild>
                                        <Button
                                            variant="outline"
                                            class="w-full justify-start text-left font-normal"
                                        >
                                            <CalendarIcon class="mr-2 h-4 w-4" />
                                            {{ filters.endDate ? formatDate(filters.endDate) : t('search.endDate') }}
                                        </Button>
                                    </PopoverTrigger>
                                    <PopoverContent class="w-auto p-0" align="start">
                                        <Calendar v-model="endDateValue" @update:model-value="handleEndDateSelect" />
                                    </PopoverContent>
                                </Popover>
                            </div>
                        </div>
                    </div>

                    <!-- 類別 -->
                    <div class="space-y-2">
                        <Label>{{ t('search.category') }}</Label>
                        <div class="grid grid-cols-3 gap-3">
                            <button
                                v-for="category in categories"
                                :key="category.id"
                                type="button"
                                @click="toggleCategory(category.id)"
                                :class="[
                                    'flex flex-col items-center gap-2 p-3 rounded-lg border-2 transition-all duration-200 press-feedback',
                                    filters.categories.includes(category.id)
                                        ? 'border-brand-primary bg-brand-accent'
                                        : 'border-border bg-background hover:border-brand-primary hover:bg-brand-accent'
                                ]"
                            >
                                <div :class="[
                                    'flex h-10 w-10 items-center justify-center rounded-lg',
                                    filters.categories.includes(category.id) ? 'bg-brand-primary' : 'bg-brand-accent'
                                ]">
                                    <component
                                        :is="category.icon"
                                        :class="[
                                            'h-5 w-5',
                                            filters.categories.includes(category.id) ? 'text-brand-primary-foreground' : 'text-brand-primary'
                                        ]"
                                    />
                                </div>
                                <span class="text-xs font-medium text-foreground">
                                    {{ category.name }}
                                </span>
                            </button>
                        </div>
                    </div>

                    <!-- 金額範圍 -->
                    <div class="space-y-3">
                        <Label>{{ t('search.amountRange') }}</Label>
                        <div class="grid grid-cols-2 gap-2">
                            <Input
                                v-model="filters.minAmount"
                                type="number"
                                :placeholder="t('search.minAmountPlaceholder')"
                                min="0"
                            />
                            <Input
                                v-model="filters.maxAmount"
                                type="number"
                                :placeholder="t('search.maxAmountPlaceholder')"
                                min="0"
                            />
                        </div>
                        <!-- 滑動條 -->
                        <div class="px-2 pt-2">
                            <Slider
                                v-model="sliderValues"
                                :max="maxPossibleAmount"
                                :step="10"
                                class="mb-2"
                            />
                            <div class="flex justify-between text-xs text-muted-foreground">
                                <span>NT$ {{ sliderValues[0] }}</span>
                                <span>NT$ {{ sliderValues[1] }}</span>
                            </div>
                        </div>
                    </div>
                </div>

                <DialogFooter>
                    <Button variant="outline" class="press-feedback" @click="resetFilters">
                        {{ t('search.reset') }}
                    </Button>
                    <Button @click="handleApplyFilters" class="bg-brand-primary hover:bg-brand-primary/90 press-feedback">
                        {{ t('search.applyFilter') }}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>

    </div>
</template>

// src/pages/expenses/ExpensesPage.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate } from '@tanstack/react-router'
import { useWindowVirtualizer } from '@tanstack/react-virtual'
import { Search, SlidersHorizontal, User, Users, RefreshCw, Plus, Wallet, HandCoins } from 'lucide-react'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { RecurringExpenseList } from '@/features/expense/components/RecurringExpenseList'
import { RecurringExpenseDrawer } from '@/features/expense/components/RecurringExpenseDrawer'
import { ExpenseGroup } from '@/features/expense/components/ExpenseGroup'
import { useExpenses } from '@/features/expense/api/useExpenses'
import type { ExpenseWithUser } from '@/features/expense/api/useExpenses'
import { useDeleteExpense } from '@/features/expense/api/useDeleteExpense'
import { useGroups } from '@/features/group/api/useGroups'
import { ScopeChips, type ExpenseScope } from '@/shared/components/ScopeChips'
import { CategoryUtils, categoryIds } from '@/features/expense/lib/categories'
import { formatCurrency } from '@/shared/lib/money'
import { cn } from '@/shared/lib/utils'
import type { DisplayExpense, RecurringExpense, CategoryId } from '@/entities/expense/types'
import type { CurrencyType } from '@/shared/lib/database.types'

const HEADER_ESTIMATE_HEIGHT = 118
const ROW_ESTIMATE_HEIGHT = 88

// 支出列表（Phase 5.1，對照 Vue ExpensesPage.vue）。搜尋 + 篩選 Dialog + personal/group/recurring
// tabs + 依日期分組列表 + 週期費用入口。走 useExpenses（作用中範疇）、useDeleteExpense（批次刪除），
// 金額一律 formatCurrency（依費用所屬群組幣別）。

type MainTab = 'personal' | 'group' | 'recurring'
type TypeFilter = 'all' | 'personal' | 'debt'

interface Filters {
    startDate: string
    endDate: string
    categories: string[]
    minAmount: string
    maxAmount: string
}

const EMPTY_FILTERS: Filters = {
    startDate: '',
    endDate: '',
    categories: [],
    minAmount: '',
    maxAmount: ''
}

export default function ExpensesPage() {
    const { t } = useTranslation()
    const navigate = useNavigate()
    const { data: expensesData, isLoading } = useExpenses()
    const { data: groupsData, isSuccess: groupsLoaded } = useGroups()
    const { deleteByDate } = useDeleteExpense()

    const isInGroup = (groupsData ?? []).length > 0

    const [activeTab, setActiveTab] = useState<MainTab>('personal')
    const [typeFilter, setTypeFilter] = useState<TypeFilter>('all')
    // 群組 tab 的群組過濾：預設全部群組；指向的群組已不在清單 → 收斂回全部。
    const [groupFilter, setGroupFilter] = useState<ExpenseScope>('all')
    useEffect(() => {
        if (
            groupFilter !== 'all' &&
            groupsLoaded &&
            !(groupsData ?? []).some((g) => g.group.id === groupFilter)
        )
            setGroupFilter('all')
    }, [groupFilter, groupsLoaded, groupsData])

    const filterCurrency: CurrencyType =
        groupFilter !== 'all'
            ? (groupsData ?? []).find((g) => g.group.id === groupFilter)?.settings?.currency ?? 'TWD'
            : 'TWD'
    const [searchQuery, setSearchQuery] = useState('')
    const [filterOpen, setFilterOpen] = useState(false)
    const [filters, setFilters] = useState<Filters>(EMPTY_FILTERS)

    const [recurringDrawerOpen, setRecurringDrawerOpen] = useState(false)
    const [editingRecurring, setEditingRecurring] = useState<RecurringExpense | null>(null)

    // group_id → { name, currency }（供群組 badge 與逐費用幣別解析）
    const groupMeta = useMemo(() => {
        const map = new Map<string, { name: string; currency: CurrencyType }>()
        for (const g of groupsData ?? []) {
            map.set(g.group.id, { name: g.group.name, currency: g.settings?.currency ?? 'TWD' })
        }
        return map
    }, [groupsData])

    const allExpenses = useMemo(() => expensesData ?? [], [expensesData])

    // 當前 tab 的來源子集
    const activeExpenses = useMemo(() => {
        if (activeTab === 'group') {
            return groupFilter === 'all'
                ? allExpenses.filter((e) => e.group_id !== null)
                : allExpenses.filter((e) => e.group_id === groupFilter)
        }
        // personal tab：all / personal（group_id null）/ debt（group_id 非 null）
        if (typeFilter === 'personal') return allExpenses.filter((e) => e.group_id === null)
        if (typeFilter === 'debt') return allExpenses.filter((e) => e.group_id !== null)
        return allExpenses
    }, [activeTab, typeFilter, allExpenses, groupFilter])

    const hasActiveFilters =
        searchQuery.trim() !== '' ||
        filters.categories.length > 0 ||
        filters.startDate !== '' ||
        filters.endDate !== '' ||
        filters.minAmount !== '' ||
        filters.maxAmount !== ''

    // single-pass 篩選
    const filtered = useMemo(() => {
        const q = searchQuery.trim().toLowerCase()
        const min = filters.minAmount ? parseFloat(filters.minAmount) : null
        const max = filters.maxAmount ? parseFloat(filters.maxAmount) : null
        return activeExpenses.filter(
            (e) =>
                (!q || e.title.toLowerCase().includes(q)) &&
                (!filters.startDate || e.date >= filters.startDate) &&
                (!filters.endDate || e.date <= filters.endDate) &&
                (filters.categories.length === 0 || filters.categories.includes(e.category)) &&
                (min === null || e.amount >= min) &&
                (max === null || e.amount <= max)
        )
    }, [activeExpenses, searchQuery, filters])

    // 依日期分組（YYYY-MM-DD 分桶，顯示以 / 分隔，降冪）
    const groups = useMemo(() => {
        const currencyOf = (e: ExpenseWithUser): CurrencyType =>
            e.currency ?? (e.group_id ? groupMeta.get(e.group_id)?.currency ?? 'TWD' : 'TWD')
        const byDate = new Map<string, DisplayExpense[]>()
        for (const e of filtered) {
            const currency = currencyOf(e)
            const list = byDate.get(e.date) ?? []
            list.push({
                id: e.id,
                title: e.title,
                amount: formatCurrency(e.amount, currency),
                numericAmount: e.amount,
                currency,
                category: e.category,
                icon: CategoryUtils.getIconKey(e.category),
                user: e.user,
                groupId: e.group_id,
                groupName: e.group_id ? groupMeta.get(e.group_id)?.name ?? null : null,
                splitMethod: e.split_method,
                isSettled: e.is_settled
            })
            byDate.set(e.date, list)
        }
        return [...byDate.entries()]
            .map(([date, exps]) => ({ date, display: date.replace(/-/g, '/'), expenses: exps }))
            .sort((a, b) => b.date.localeCompare(a.date))
    }, [filtered, activeTab, groupMeta])

    const toggleCategory = (id: string) => {
        setFilters((f) => ({
            ...f,
            categories: f.categories.includes(id)
                ? f.categories.filter((c) => c !== id)
                : [...f.categories, id]
        }))
    }

    const resetFilters = () => {
        setFilters(EMPTY_FILTERS)
        setSearchQuery('')
    }

    const handleDeleteAll = (expenses: DisplayExpense[]) => {
        void deleteByDate.mutateAsync({
            expenseIds: expenses.map((e) => e.id),
            groupIds: expenses.map((e) => e.groupId).filter((id): id is string => !!id)
        })
    }

    const openAddRecurring = () => {
        setEditingRecurring(null)
        setRecurringDrawerOpen(true)
    }
    const openEditRecurring = (item: RecurringExpense) => {
        setEditingRecurring(item)
        setRecurringDrawerOpen(true)
    }

    const typeFilterButtons: ReadonlyArray<{ value: TypeFilter; label: string; icon: typeof Wallet | null }> = [
        { value: 'all', label: t('dashboard.filterAll'), icon: null },
        { value: 'personal', label: t('dashboard.filterPersonal'), icon: Wallet },
        { value: 'debt', label: t('dashboard.filterDebt'), icon: HandCoins }
    ]

    const emptyText = hasActiveFilters
        ? t('search.noResultsFound')
        : activeTab === 'group'
          ? t('expenses.noGroupExpenses')
          : t('expenses.noPersonalExpenses')

    return (
        <div>
            {/* 搜尋列 */}
            <div className="sticky top-[52px] z-30 bg-background/80 px-4 py-3 backdrop-blur-xl">
                <div className="glass flex gap-2 rounded-full p-1.5">
                    <div className="relative flex-1">
                        <Search className="absolute top-1/2 left-3 h-5 w-5 -translate-y-1/2 text-muted-foreground" />
                        <Input
                            type="text"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            placeholder={t('search.searchTransaction')}
                            aria-label={t('search.searchTransaction')}
                            className="h-11 border-0 bg-transparent pr-4 pl-10 shadow-none focus-visible:ring-0"
                        />
                    </div>
                    <div className="relative">
                        <Button
                            variant="outline"
                            size="icon"
                            className="press-feedback hover-transition h-11 w-11 rounded-full"
                            aria-label={t('search.filterConditions')}
                            onClick={() => setFilterOpen(true)}
                        >
                            <SlidersHorizontal className="h-5 w-5" />
                        </Button>
                        {hasActiveFilters && (
                            <span className="absolute -top-0.5 -right-0.5 h-2.5 w-2.5 rounded-full bg-red-500" />
                        )}
                    </div>
                </div>
            </div>

            <main className="px-4 pb-28">
                <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as MainTab)} className="mt-4">
                    <TabsList className="glass-light grid w-full grid-cols-3 rounded-full p-[2px]">
                        <TabsTrigger value="personal" className="press-feedback flex items-center gap-2 rounded-full">
                            <User className="h-4 w-4" />
                            {t('expense.personal')}
                        </TabsTrigger>
                        <TabsTrigger
                            value="group"
                            disabled={!isInGroup}
                            className="press-feedback flex items-center gap-2 rounded-full"
                        >
                            <Users className="h-4 w-4" />
                            {t('expense.group')}
                        </TabsTrigger>
                        <TabsTrigger value="recurring" className="press-feedback flex items-center gap-2 rounded-full">
                            <RefreshCw className="h-4 w-4" />
                            {t('recurring.title')}
                        </TabsTrigger>
                    </TabsList>

                    {/* 個人 */}
                    <TabsContent value="personal" className="mt-4">
                        <div className="mb-4 flex gap-2">
                            {typeFilterButtons.map((f) => (
                                <button
                                    key={f.value}
                                    type="button"
                                    onClick={() => setTypeFilter(f.value)}
                                    aria-pressed={typeFilter === f.value}
                                    className={cn(
                                        'press-feedback flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-sm font-medium transition-all duration-200',
                                        typeFilter === f.value
                                            ? 'bg-primary text-primary-foreground shadow-sm'
                                            : 'glass text-muted-foreground hover:text-foreground'
                                    )}
                                >
                                    {f.icon && <f.icon className="h-3.5 w-3.5" />}
                                    {f.label}
                                </button>
                            ))}
                        </div>
                        <ExpenseListBody
                            isLoading={isLoading}
                            groups={groups}
                            showUser={false}
                            currency={'TWD'}
                            emptyText={emptyText}
                            emptyIcon={<User className="mx-auto mb-4 h-12 w-12 text-muted-foreground/50" />}
                            onExpenseClick={(id) => navigate({ to: '/expenses/$id', params: { id } })}
                            onDeleteAll={handleDeleteAll}
                        />
                    </TabsContent>

                    {/* 群組 */}
                    <TabsContent value="group" className="mt-4">
                        {isInGroup && (
                            <ScopeChips
                                className="mb-4"
                                value={groupFilter}
                                onChange={setGroupFilter}
                                groups={(groupsData ?? []).map((g) => ({
                                    id: g.group.id,
                                    name: g.group.name
                                }))}
                                includePersonal={false}
                            />
                        )}
                        <ExpenseListBody
                            isLoading={isLoading}
                            groups={groups}
                            showUser
                            currency={filterCurrency}
                            emptyText={emptyText}
                            emptyIcon={<Users className="mx-auto mb-4 h-12 w-12 text-muted-foreground/50" />}
                            onExpenseClick={(id) => navigate({ to: '/expenses/$id', params: { id } })}
                            onDeleteAll={handleDeleteAll}
                        />
                    </TabsContent>

                    {/* 週期費用 */}
                    <TabsContent value="recurring" className="mt-4">
                        <div className="mb-3 flex justify-end">
                            <Button size="sm" className="press-feedback gap-2 rounded-full" onClick={openAddRecurring}>
                                <Plus className="h-4 w-4" />
                                {t('recurring.add')}
                            </Button>
                        </div>
                        <RecurringExpenseList onEdit={openEditRecurring} />
                    </TabsContent>
                </Tabs>
            </main>

            <RecurringExpenseDrawer
                open={recurringDrawerOpen}
                onOpenChange={setRecurringDrawerOpen}
                editItem={editingRecurring}
            />

            {/* 篩選 Dialog */}
            <Dialog open={filterOpen} onOpenChange={setFilterOpen}>
                <DialogContent className="bg-card sm:max-w-md">
                    <DialogHeader>
                        <DialogTitle>{t('search.filterConditions')}</DialogTitle>
                        <DialogDescription>{t('search.setFilterDesc')}</DialogDescription>
                    </DialogHeader>

                    <div className="grid gap-4 py-4">
                        {/* 日期範圍 */}
                        <div className="space-y-2">
                            <Label>{t('search.dateRange')}</Label>
                            <div className="grid grid-cols-2 gap-2">
                                <Input
                                    type="date"
                                    value={filters.startDate}
                                    aria-label={t('search.startDate')}
                                    onChange={(e) => setFilters((f) => ({ ...f, startDate: e.target.value }))}
                                />
                                <Input
                                    type="date"
                                    value={filters.endDate}
                                    aria-label={t('search.endDate')}
                                    onChange={(e) => setFilters((f) => ({ ...f, endDate: e.target.value }))}
                                />
                            </div>
                        </div>

                        {/* 類別 */}
                        <div className="space-y-2">
                            <Label>{t('search.category')}</Label>
                            <div className="grid grid-cols-3 gap-3">
                                {categoryIds.map((id: CategoryId) => {
                                    const Icon = CategoryUtils.getIconByCategory(id)
                                    const selected = filters.categories.includes(id)
                                    return (
                                        <button
                                            key={id}
                                            type="button"
                                            onClick={() => toggleCategory(id)}
                                            aria-pressed={selected}
                                            className={cn(
                                                'press-feedback flex flex-col items-center gap-2 rounded-lg border-2 p-3 transition-all duration-200',
                                                selected
                                                    ? 'border-brand-primary bg-brand-accent'
                                                    : 'border-border bg-background hover:border-brand-primary'
                                            )}
                                        >
                                            <span
                                                className={cn(
                                                    'flex h-10 w-10 items-center justify-center rounded-lg',
                                                    selected ? 'bg-brand-primary' : 'bg-brand-accent'
                                                )}
                                            >
                                                <Icon
                                                    className={cn(
                                                        'h-5 w-5',
                                                        selected ? 'text-brand-primary-foreground' : 'text-brand-primary'
                                                    )}
                                                />
                                            </span>
                                            <span className="text-xs font-medium text-foreground">
                                                {t(`expense.categories.${id}`)}
                                            </span>
                                        </button>
                                    )
                                })}
                            </div>
                        </div>

                        {/* 金額範圍 */}
                        <div className="space-y-2">
                            <Label>{t('search.amountRange')}</Label>
                            <div className="grid grid-cols-2 gap-2">
                                <Input
                                    type="number"
                                    min="0"
                                    value={filters.minAmount}
                                    placeholder={t('search.minAmountPlaceholder')}
                                    aria-label={t('search.minAmount')}
                                    onChange={(e) => setFilters((f) => ({ ...f, minAmount: e.target.value }))}
                                />
                                <Input
                                    type="number"
                                    min="0"
                                    value={filters.maxAmount}
                                    placeholder={t('search.maxAmountPlaceholder')}
                                    aria-label={t('search.maxAmount')}
                                    onChange={(e) => setFilters((f) => ({ ...f, maxAmount: e.target.value }))}
                                />
                            </div>
                        </div>
                    </div>

                    <DialogFooter>
                        <Button variant="outline" className="press-feedback" onClick={resetFilters}>
                            {t('search.reset')}
                        </Button>
                        <Button
                            className="press-feedback bg-brand-primary hover:bg-brand-primary/90"
                            onClick={() => setFilterOpen(false)}
                        >
                            {t('search.applyFilter')}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    )
}

// 列表主體：載入骨架 / 分組清單 / 空狀態
interface ListBodyProps {
    isLoading: boolean
    groups: { date: string; display: string; expenses: DisplayExpense[] }[]
    showUser: boolean
    currency: CurrencyType
    emptyText: string
    emptyIcon: ReactNode
    onExpenseClick: (id: string) => void
    onDeleteAll: (expenses: DisplayExpense[]) => void
}

function ExpenseListBody({
    isLoading,
    groups,
    showUser,
    currency,
    emptyText,
    emptyIcon,
    onExpenseClick,
    onDeleteAll
}: ListBodyProps) {
    const listOffsetRef = useRef(0)
    const listRef = useRef<HTMLDivElement>(null)

    const virtualizer = useWindowVirtualizer({
        count: groups.length,
        getItemKey: (index) => groups[index]?.date ?? `group-${index}`,
        estimateSize: (index) => {
            const group = groups[index]
            if (!group) return HEADER_ESTIMATE_HEIGHT
            return HEADER_ESTIMATE_HEIGHT + group.expenses.length * ROW_ESTIMATE_HEIGHT
        },
        overscan: 5,
        // 對齊改動前清單的 space-y-4（1rem）群組間距：絕對定位下 wrapper 之間沒有 CSS 間距，
        // 由 virtualizer 的 gap 在 start 計算中補上，否則卡片會相貼。
        gap: 16,
        initialRect: process.env.NODE_ENV === 'test' ? { width: 1024, height: 768 } : undefined,
        ...(process.env.NODE_ENV === 'test'
            ? {
                    measureElement: (element: Element, entry?: ResizeObserverEntry) => {
                        const measuredHeight =
                            entry?.contentBoxSize?.[0]?.blockSize ??
                            entry?.borderBoxSize?.[0]?.blockSize ??
                            Number(entry?.contentRect?.height)

                        if (Number.isFinite(measuredHeight) && measuredHeight > 0) return measuredHeight

                        const index = Number((element as HTMLElement).dataset?.index)
                        if (!Number.isInteger(index)) return HEADER_ESTIMATE_HEIGHT

                        const group = groups[index]
                        if (!group) return HEADER_ESTIMATE_HEIGHT
                        return HEADER_ESTIMATE_HEIGHT + group.expenses.length * ROW_ESTIMATE_HEIGHT
                    }
              }
            : {}),
        scrollMargin: listOffsetRef.current
    })

    useEffect(() => {
        const listElement = listRef.current
        if (!listElement) return

        const updateScrollMargin = () => {
            const rect = listElement.getBoundingClientRect()
            const nextScrollMargin = rect.top + window.scrollY

            if (listOffsetRef.current === nextScrollMargin) return
            listOffsetRef.current = nextScrollMargin
            virtualizer.setOptions({
                ...virtualizer.options,
                scrollMargin: nextScrollMargin
            })
            virtualizer.measure()
        }

        updateScrollMargin()
        window.addEventListener('resize', updateScrollMargin)
        return () => window.removeEventListener('resize', updateScrollMargin)
    }, [virtualizer])

    if (isLoading) {
        return (
            <div className="space-y-4">
                {[0, 1, 2].map((i) => (
                    <div key={i} className="glass space-y-3 rounded-2xl p-4">
                        <div className="h-4 w-24 animate-pulse rounded bg-muted" />
                        <div className="h-10 animate-pulse rounded-lg bg-muted" />
                        <div className="h-10 animate-pulse rounded-lg bg-muted" />
                    </div>
                ))}
            </div>
        )
    }

    if (groups.length === 0) {
        return (
            <div className="py-12 text-center">
                {emptyIcon}
                <p className="mb-4 text-muted-foreground">{emptyText}</p>
            </div>
        )
    }

    return (
        <div className="relative w-full">
            <div className="relative w-full" ref={listRef} style={{ height: `${virtualizer.getTotalSize()}px` }}>
                {virtualizer.getVirtualItems().map((virtualItem) => {
                    const group = groups[virtualItem.index]

                    if (!group) return null

                    return (
                        <div
                            key={virtualItem.key}
                            data-virtual-item="true"
                            data-index={virtualItem.index}
                            ref={virtualizer.measureElement}
                            style={{
                                position: 'absolute',
                                top: 0,
                                left: 0,
                                width: '100%',
                                transform: `translateY(${virtualItem.start - virtualizer.options.scrollMargin}px)`
                            }}
                        >
                            <ExpenseGroup
                                date={group.display}
                                expenses={group.expenses}
                                showUser={showUser}
                                currency={currency}
                                onExpenseClick={onExpenseClick}
                                onDeleteAll={onDeleteAll}
                            />
                        </div>
                    )
                })}
            </div>
        </div>
    )
}
