// src/features/expense/components/RecurringExpenseDrawer.vue
<template>
    <Drawer v-model:open="isOpen">
        <DrawerContent class="max-h-[90vh] flex flex-col bg-card !border-0 !border-t border-glass-border-strong">

            <!-- Header -->
            <DrawerHeader class="text-center pb-2 shrink-0">
                <DrawerTitle class="text-xl font-semibold text-foreground">
                    {{ isEdit ? t('recurring.edit') : t('recurring.add') }}
                </DrawerTitle>
                <DrawerDescription class="text-xs text-muted-foreground mt-1">
                    {{ t('recurring.emptyDesc') }}
                </DrawerDescription>
            </DrawerHeader>

            <!-- Form content (scrollable) -->
            <div class="flex-1 overflow-y-auto px-4">
                <form class="space-y-4 pb-4 pt-2" @submit.prevent="handleSubmit">

                    <!-- Title -->
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-foreground">
                            {{ t('expense.title') }}
                        </label>
                        <Input
                            v-model="form.title"
                            :placeholder="t('expense.titlePlaceholder')"
                            class="h-12"
                            autocomplete="off"
                        />
                    </div>

                    <!-- Amount -->
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-foreground">
                            {{ t('expense.amount') }} (NT$)
                        </label>
                        <div class="relative">
                            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm font-medium">
                                NT$
                            </span>
                            <Input
                                v-model="form.amount"
                                type="number"
                                min="0"
                                step="1"
                                placeholder="0"
                                class="h-12 pl-10"
                            />
                        </div>
                    </div>

                    <!-- Category grid -->
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-foreground">
                            {{ t('expense.category') }}
                        </label>
                        <div class="grid grid-cols-3 gap-2.5">
                            <button
                                v-for="cat in categories"
                                :key="cat.id"
                                type="button"
                                @click="form.category = cat.id as CategoryId"
                                :class="[
                                    'flex flex-col items-center gap-2 p-3 rounded-xl border-2 transition-all duration-200 press-feedback',
                                    form.category === cat.id
                                        ? 'glass-heavy'
                                        : 'border-transparent glass-light hover:glass'
                                ]"
                                :style="form.category === cat.id
                                    ? { borderColor: 'var(--category-' + cat.id + ')' }
                                    : undefined
                                "
                            >
                                <div
                                    class="flex h-10 w-10 items-center justify-center rounded-xl"
                                    :style="form.category === cat.id
                                        ? { backgroundColor: 'var(--category-' + cat.id + ')' }
                                        : { backgroundColor: 'var(--category-' + cat.id + '-bg)' }
                                    "
                                >
                                    <component
                                        :is="CategoryUtils.getIconByKey(cat.iconKey)"
                                        class="h-5 w-5"
                                        :style="form.category === cat.id
                                            ? { color: 'white' }
                                            : { color: 'var(--category-' + cat.id + ')' }
                                        "
                                    />
                                </div>
                                <span class="text-xs font-medium text-foreground leading-tight text-center">
                                    {{ cat.name }}
                                </span>
                            </button>
                        </div>
                    </div>

                    <!-- Recurrence day -->
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-foreground">
                            {{ t('recurring.recurrenceDay') }}
                        </label>
                        <Input
                            v-model="form.recurrence_day"
                            type="number"
                            min="1"
                            max="31"
                            :placeholder="t('recurring.recurrenceDayPlaceholder')"
                            class="h-12"
                        />
                        <p v-if="nextDueDatePreview" class="text-xs text-muted-foreground">
                            {{ t('recurring.nextDueDate') }}：{{ nextDueDatePreview }}
                        </p>
                    </div>

                    <!-- Notes -->
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-foreground">
                            {{ t('expense.notes') }}
                            <span class="text-muted-foreground text-xs">({{ t('common.optional') }})</span>
                        </label>
                        <Input
                            v-model="form.notes"
                            :placeholder="t('expense.notesPlaceholder')"
                            class="h-12"
                        />
                    </div>
                </form>
            </div>

            <!-- Footer actions (fixed at bottom) -->
            <div class="px-4 py-4 bg-card border-t border-border shrink-0">
                <div class="flex gap-3">
                    <Button
                        variant="outline"
                        class="flex-1 h-12 text-foreground border-border hover:bg-accent"
                        type="button"
                        @click="isOpen = false"
                    >
                        {{ t('common.cancel') }}
                    </Button>
                    <Button
                        :disabled="!isValid || isSubmitting"
                        class="flex-1 h-12 bg-brand-primary hover:bg-brand-primary/90 text-brand-primary-foreground disabled:opacity-50 press-feedback"
                        type="button"
                        @click="handleSubmit"
                    >
                        {{ isSubmitting ? t('common.saving') : t('common.save') }}
                    </Button>
                </div>
            </div>

        </DrawerContent>
    </Drawer>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription
} from '@/shared/components/ui/drawer'
import { Button } from '@/shared/components/ui/button'
import { Input } from '@/shared/components/ui/input'
import { useRecurringExpenseStore } from '@/shared/stores'
import { useCategories, CategoryUtils } from '@/features/expense/composables/useCategories'
import type { RecurringExpense, CreateRecurringExpenseData, UpdateRecurringExpenseData } from '@/entities/expense/types'
import type { CategoryId } from '@/entities/expense/types'
import { toast } from 'vue-sonner'

// ---------------------------------------------------------------------------
// Props & emits
// ---------------------------------------------------------------------------

const props = defineProps<{
    open: boolean
    editItem?: RecurringExpense | null
}>()

const emit = defineEmits<{
    'update:open': [value: boolean]
    saved: []
}>()

// ---------------------------------------------------------------------------
// i18n + stores + composables
// ---------------------------------------------------------------------------

const { t } = useI18n()
const recurringStore = useRecurringExpenseStore()
const { categories } = useCategories()

// ---------------------------------------------------------------------------
// Drawer open state
// ---------------------------------------------------------------------------

const isOpen = computed({
    get: () => props.open,
    set: (v) => emit('update:open', v)
})

const isEdit = computed(() => !!props.editItem)

// ---------------------------------------------------------------------------
// Form data
// ---------------------------------------------------------------------------

const form = ref({
    title: '',
    amount: '',
    category: 'other' as CategoryId,
    recurrence_day: '',
    notes: ''
})

const isSubmitting = ref(false)

// ---------------------------------------------------------------------------
// Auto-calculate next_due_date from recurrence_day
// ---------------------------------------------------------------------------

function formatLocalDate(d: Date): string {
    const y = d.getFullYear()
    const m = String(d.getMonth() + 1).padStart(2, '0')
    const day = String(d.getDate()).padStart(2, '0')
    return `${y}-${m}-${day}`
}

function computeNextDueDate(day: number): string {
    const today = new Date()
    const year = today.getFullYear()
    const month = today.getMonth()

    const daysInThisMonth = new Date(year, month + 1, 0).getDate()
    const clampedDay = Math.min(day, daysInThisMonth)
    const thisMonthDate = new Date(year, month, clampedDay)

    if (thisMonthDate > today) {
        return formatLocalDate(thisMonthDate)
    }

    const nextMonth = month + 1
    const nextYear = nextMonth > 11 ? year + 1 : year
    const normalizedMonth = nextMonth > 11 ? 0 : nextMonth
    const daysInNextMonth = new Date(nextYear, normalizedMonth + 1, 0).getDate()
    const clampedNextDay = Math.min(day, daysInNextMonth)
    const nextMonthDate = new Date(nextYear, normalizedMonth, clampedNextDay)
    return formatLocalDate(nextMonthDate)
}

const nextDueDatePreview = computed(() => {
    const day = parseInt(form.value.recurrence_day)
    if (isNaN(day) || day < 1 || day > 31) return ''
    const dateStr = computeNextDueDate(day)
    const date = new Date(dateStr + 'T00:00:00')
    return date.toLocaleDateString('zh-TW', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    })
})

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

const isValid = computed(() => {
    const day = parseInt(form.value.recurrence_day)
    return (
        form.value.title.trim() !== ''
        && parseFloat(form.value.amount) > 0
        && !isNaN(day) && day >= 1 && day <= 31
    )
})

// ---------------------------------------------------------------------------
// Form reset
// ---------------------------------------------------------------------------

function resetForm() {
    const today = new Date()
    form.value = {
        title: '',
        amount: '',
        category: 'other',
        recurrence_day: String(today.getDate()),
        notes: ''
    }
}

// ---------------------------------------------------------------------------
// Lifecycle watchers
// ---------------------------------------------------------------------------

watch(() => props.editItem, (item) => {
    if (item) {
        form.value = {
            title: item.title,
            amount: String(item.amount),
            category: item.category,
            recurrence_day: String(item.recurrence_day),
            notes: item.notes ?? ''
        }
    } else {
        resetForm()
    }
}, { immediate: true })

watch(() => props.open, (open) => {
    if (open && !props.editItem) {
        resetForm()
    }
})

// ---------------------------------------------------------------------------
// Submit
// ---------------------------------------------------------------------------

async function handleSubmit() {
    if (!isValid.value || isSubmitting.value) return
    isSubmitting.value = true

    const day = parseInt(form.value.recurrence_day)
    const nextDueDate = computeNextDueDate(day)

    try {
        if (isEdit.value && props.editItem) {
            const payload: UpdateRecurringExpenseData = {
                title: form.value.title.trim(),
                amount: parseFloat(form.value.amount),
                category: form.value.category,
                recurrence_day: day,
                next_due_date: nextDueDate,
                notes: form.value.notes.trim() || undefined
            }
            const ok = await recurringStore.update(props.editItem.id, payload)
            if (ok) {
                toast.success(t('recurring.updateSuccess'))
                emit('saved')
                isOpen.value = false
            } else {
                toast.error(recurringStore.error ?? t('recurring.updateError'))
            }
        } else {
            const payload: CreateRecurringExpenseData = {
                title: form.value.title.trim(),
                amount: parseFloat(form.value.amount),
                category: form.value.category,
                recurrence_day: day,
                next_due_date: nextDueDate,
                notes: form.value.notes.trim() || undefined
            }
            const created = await recurringStore.create(payload)
            if (created) {
                toast.success(t('recurring.createSuccess'))
                emit('saved')
                isOpen.value = false
            } else {
                toast.error(recurringStore.error ?? t('recurring.createError'))
            }
        }
    } finally {
        isSubmitting.value = false
    }
}
</script>

// src/features/expense/components/RecurringExpenseDrawer.tsx
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription
} from '@/components/ui/drawer'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { CategoryUtils, categoryIds } from '@/features/expense/lib/categories'
import { formatCurrency } from '@/shared/lib/money'
import { taipeiDateString } from '@/shared/lib/datetime'
import { cn } from '@/shared/lib/utils'
import {
    useCreateRecurringExpense,
    useUpdateRecurringExpense
} from '@/features/expense/api/recurring'
import { useActiveGroup, useGroups } from '@/features/group/api/useGroups'
import type {
    RecurringExpense,
    CreateRecurringExpenseData,
    UpdateRecurringExpenseData,
    CategoryId
} from '@/entities/expense/types'
import type { CurrencyType } from '@/shared/lib/database.types'

// 週期費用新增/編輯抽屜（Phase 5.1，對照 Vue RecurringExpenseDrawer.vue）。
// 走 Phase 4 useCreateRecurringExpense / useUpdateRecurringExpense。next_due_date 由 recurrence_day
// 以 Taipei 日曆基準推算（對齊 recurring.ts:computeNextDueDate，避免裝置時區飄日）。

interface Props {
    open: boolean
    onOpenChange: (open: boolean) => void
    editItem?: RecurringExpense | null
}

const pad2 = (n: number): string => String(n).padStart(2, '0')

// 依 recurrence_day 推算下次到期日（Taipei 基準、含當日、月底截斷），對齊 recurring.ts 的私有實作。
function computeNextDueDate(day: number): string {
    const [year, month, today] = taipeiDateString().split('-').map(Number)
    const daysInThisMonth = new Date(Date.UTC(year!, month!, 0)).getUTCDate()
    const clampedDay = Math.min(day, daysInThisMonth)
    if (clampedDay >= today!) {
        return `${year}-${pad2(month!)}-${pad2(clampedDay)}`
    }
    const nextMonth = month! === 12 ? 1 : month! + 1
    const nextYear = month! === 12 ? year! + 1 : year!
    const daysInNextMonth = new Date(Date.UTC(nextYear, nextMonth, 0)).getUTCDate()
    const clampedNextDay = Math.min(day, daysInNextMonth)
    return `${nextYear}-${pad2(nextMonth)}-${pad2(clampedNextDay)}`
}

const DEFAULT_CATEGORY: CategoryId = 'other'

export function RecurringExpenseDrawer({ open, onOpenChange, editItem }: Props) {
    const { t } = useTranslation()
    const { activeGroupId } = useActiveGroup()
    const { data: groupsData } = useGroups()
    const create = useCreateRecurringExpense()
    const update = useUpdateRecurringExpense()
    const isEdit = !!editItem

    const [title, setTitle] = useState('')
    const [amount, setAmount] = useState('')
    const [category, setCategory] = useState<CategoryId>(DEFAULT_CATEGORY)
    const [recurrenceDay, setRecurrenceDay] = useState('')
    const [notes, setNotes] = useState('')
    const [submitting, setSubmitting] = useState(false)

    // 開啟時初始化：編輯帶入既有值；新增回填「今天的號數」為預設 recurrence_day。
    useEffect(() => {
        if (!open) return
        if (editItem) {
            setTitle(editItem.title)
            setAmount(String(editItem.amount))
            setCategory(editItem.category)
            setRecurrenceDay(String(editItem.recurrence_day))
            setNotes(editItem.notes ?? '')
        } else {
            const [, , todayDay] = taipeiDateString().split('-')
            setTitle('')
            setAmount('')
            setCategory(DEFAULT_CATEGORY)
            setRecurrenceDay(todayDay ?? '')
            setNotes('')
        }
    }, [open, editItem])

    const groupCurrencies = useMemo(() => {
        const map = new Map<string, CurrencyType>()
        for (const g of groupsData ?? []) {
            if (g.settings?.currency) {
                map.set(g.group.id, g.settings.currency)
            }
        }
        return map
    }, [groupsData])
    const currency = editItem
        ? editItem.group_id
            ? groupCurrencies.get(editItem.group_id) ?? 'TWD'
            : 'TWD'
        : activeGroupId
            ? groupCurrencies.get(activeGroupId) ?? null
            : 'TWD'
    const currencyReady = currency !== null
    const currencySymbol = useMemo(
        () => currency ? formatCurrency(0, currency).replace(/[\d.,\s]/g, '') : '',
        [currency]
    )

    const dayNum = parseInt(recurrenceDay, 10)
    const amountNum = parseFloat(amount)
    const isValid =
        currencyReady &&
        title.trim() !== '' &&
        Number.isFinite(amountNum) &&
        amountNum > 0 &&
        !Number.isNaN(dayNum) &&
        dayNum >= 1 &&
        dayNum <= 31

    const nextDuePreview = isValid ? computeNextDueDate(dayNum) : ''

    const handleSubmit = async () => {
        if (!isValid || submitting) return
        setSubmitting(true)
        const nextDueDate = computeNextDueDate(dayNum)
        try {
            if (isEdit && editItem) {
                const payload: UpdateRecurringExpenseData = {
                    title: title.trim(),
                    amount: amountNum,
                    category,
                    recurrence_day: dayNum,
                    next_due_date: nextDueDate,
                    notes: notes.trim() || undefined
                }
                await update.mutateAsync({ id: editItem.id, payload })
                toast.success(t('recurring.updateSuccess'))
            } else {
                const payload: CreateRecurringExpenseData = {
                    title: title.trim(),
                    amount: amountNum,
                    category,
                    recurrence_day: dayNum,
                    next_due_date: nextDueDate,
                    notes: notes.trim() || undefined
                }
                await create.mutateAsync(payload)
                toast.success(t('recurring.createSuccess'))
            }
            onOpenChange(false)
        } catch {
            toast.error(isEdit ? t('recurring.updateError') : t('recurring.createError'))
        } finally {
            setSubmitting(false)
        }
    }

    return (
        <Drawer open={open} onOpenChange={onOpenChange}>
            <DrawerContent className="flex max-h-[90vh] flex-col border-t border-glass-border-strong bg-card">
                <DrawerHeader className="shrink-0 pb-2 text-center">
                    <DrawerTitle className="text-xl font-semibold text-foreground">
                        {isEdit ? t('recurring.edit') : t('recurring.add')}
                    </DrawerTitle>
                    <DrawerDescription className="mt-1 text-xs text-muted-foreground">
                        {t('recurring.emptyDesc')}
                    </DrawerDescription>
                </DrawerHeader>

                <div className="flex-1 overflow-y-auto px-4">
                    <div className="space-y-4 pt-2 pb-4">
                        {/* 標題 */}
                        <div className="space-y-1.5">
                            <label htmlFor="recurring-title" className="text-sm font-medium text-foreground">
                                {t('expense.title')}
                            </label>
                            <Input
                                id="recurring-title"
                                value={title}
                                onChange={(e) => setTitle(e.target.value)}
                                placeholder={t('expense.titlePlaceholder')}
                                className="h-12"
                                autoComplete="off"
                            />
                        </div>

                        {/* 金額 */}
                        <div className="space-y-1.5">
                            <label htmlFor="recurring-amount" className="text-sm font-medium text-foreground">
                                {t('expense.amount')}
                            </label>
                            <div className="relative">
                                <span className="absolute top-1/2 left-3 -translate-y-1/2 text-sm font-medium text-muted-foreground">
                                    {currencyReady ? currencySymbol : t('common.loading')}
                                </span>
                                <Input
                                    id="recurring-amount"
                                    type="number"
                                    inputMode="numeric"
                                    value={amount}
                                    onChange={(e) => setAmount(e.target.value)}
                                    placeholder="0"
                                    min="0"
                                    step="1"
                                    className="h-12 pl-12"
                                />
                            </div>
                        </div>

                        {/* 類別 */}
                        <div className="space-y-1.5">
                            <label className="text-sm font-medium text-foreground">
                                {t('expense.category')}
                            </label>
                            <div className="grid grid-cols-3 gap-2.5">
                                {categoryIds.map((id) => {
                                    const Icon = CategoryUtils.getIconByCategory(id)
                                    const selected = category === id
                                    return (
                                        <button
                                            key={id}
                                            type="button"
                                            onClick={() => setCategory(id)}
                                            aria-pressed={selected}
                                            className={cn(
                                                'press-feedback flex flex-col items-center gap-2 rounded-xl border-2 p-3 transition-all duration-200',
                                                selected ? 'glass-heavy' : 'glass-light border-transparent hover:glass'
                                            )}
                                            style={selected ? { borderColor: CategoryUtils.getCategoryColor(id) } : undefined}
                                        >
                                            <span
                                                className="flex h-10 w-10 items-center justify-center rounded-xl"
                                                style={{
                                                    backgroundColor: selected
                                                        ? CategoryUtils.getCategoryColor(id)
                                                        : CategoryUtils.getCategoryBgColor(id)
                                                }}
                                            >
                                                <Icon
                                                    className="h-5 w-5"
                                                    style={{ color: selected ? 'white' : CategoryUtils.getCategoryColor(id) }}
                                                />
                                            </span>
                                            <span className="text-center text-xs leading-tight font-medium text-foreground">
                                                {t(`expense.categories.${id}`)}
                                            </span>
                                        </button>
                                    )
                                })}
                            </div>
                        </div>

                        {/* 每月幾號 */}
                        <div className="space-y-1.5">
                            <label htmlFor="recurring-day" className="text-sm font-medium text-foreground">
                                {t('recurring.recurrenceDay')}
                            </label>
                            <Input
                                id="recurring-day"
                                type="number"
                                inputMode="numeric"
                                value={recurrenceDay}
                                onChange={(e) => setRecurrenceDay(e.target.value)}
                                min="1"
                                max="31"
                                placeholder={t('recurring.recurrenceDayPlaceholder')}
                                className="h-12"
                            />
                            {nextDuePreview && (
                                <p className="text-xs text-muted-foreground">
                                    {t('recurring.nextDueDate')}: {nextDuePreview}
                                </p>
                            )}
                        </div>

                        {/* 備註 */}
                        <div className="space-y-1.5">
                            <label htmlFor="recurring-notes" className="text-sm font-medium text-foreground">
                                {t('expense.notes')}{' '}
                                <span className="text-xs text-muted-foreground">({t('common.optional')})</span>
                            </label>
                            <Input
                                id="recurring-notes"
                                value={notes}
                                onChange={(e) => setNotes(e.target.value)}
                                placeholder={t('expense.notesPlaceholder')}
                                className="h-12"
                            />
                        </div>
                    </div>
                </div>

                <div className="shrink-0 border-t border-border bg-card px-4 py-4">
                    <div className="flex gap-3">
                        <Button
                            variant="outline"
                            type="button"
                            onClick={() => onOpenChange(false)}
                            className="h-12 flex-1 border-border text-foreground hover:bg-accent"
                        >
                            {t('common.cancel')}
                        </Button>
                        <Button
                            type="button"
                            onClick={handleSubmit}
                            disabled={!isValid || submitting}
                            className="press-feedback h-12 flex-1 bg-brand-primary text-brand-primary-foreground hover:bg-brand-primary/90 disabled:opacity-50"
                        >
                            {submitting ? t('common.saving') : t('common.save')}
                        </Button>
                    </div>
                </div>
            </DrawerContent>
        </Drawer>
    )
}
