// src/features/settlement/components/SettlementDrawer.tsx
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { HandCoins, Pencil } from 'lucide-react'
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    DrawerFooter
} from '@/components/ui/drawer'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useSettleMonthlyDebt, useUpdateSettlement } from '@/features/settlement/api/mutations'
import { formatCurrency } from '@/shared/lib/money'
import { currentYearMonth } from '@/shared/lib/datetime'
import type { CurrencyType } from '@/shared/lib/database.types'

// 結算 / 編輯結算抽屜（對照 Vue SettlementDrawer.vue）。刻意只保留兩種模式：
//   - 結算：一律走 settleMonthlyDebt（帶 yearMonth；RPC 以 auth user 為付款方，故僅 debtor 觸發）
//   - 編輯：走 updateSettlement
// 金額限正整數；結算模式上限為建議（債務）金額；成功 toast 後關閉，送出中停用確認。

interface DrawerTarget {
    userId: string
    displayName: string | null
}

interface Props {
    open: boolean
    onOpenChange: (open: boolean) => void
    groupId: string
    toUser: DrawerTarget
    suggestedAmount: number
    yearMonth: string | null
    currency: CurrencyType
    editSettlementId: string | null
    editNotes: string | null
}

export function SettlementDrawer({
    open,
    onOpenChange,
    groupId,
    toUser,
    suggestedAmount,
    yearMonth,
    currency,
    editSettlementId,
    editNotes
}: Props) {
    const { t } = useTranslation()
    const settle = useSettleMonthlyDebt()
    const update = useUpdateSettlement()
    const isEdit = !!editSettlementId

    const [amount, setAmount] = useState('')
    const [notes, setNotes] = useState('')
    const [submitting, setSubmitting] = useState(false)

    // 開啟時回填建議金額與備註（對齊 Vue watch(open) → resetSettlementForm）。
    useEffect(() => {
        if (!open) return
        setAmount(suggestedAmount > 0 ? String(suggestedAmount) : '')
        setNotes(editNotes ?? '')
        setSubmitting(false)
    }, [open, suggestedAmount, editNotes])

    const currencySymbol = useMemo(
        () => formatCurrency(0, currency).replace(/[\d.,\s]/g, ''),
        [currency]
    )

    const amountNum = Number(amount)
    const isValid =
        amount.trim() !== '' &&
        Number.isInteger(amountNum) &&
        amountNum >= 1 &&
        (isEdit || amountNum <= suggestedAmount)

    const pending = submitting || settle.isPending || update.isPending

    const handleConfirm = async () => {
        if (!isValid || pending) return
        setSubmitting(true)
        try {
            if (isEdit && editSettlementId) {
                await update.mutateAsync({
                    settlementId: editSettlementId,
                    groupId,
                    amount: amountNum,
                    notes: notes.trim() || undefined
                })
                toast.success(t('settlement.editSuccess'))
            } else {
                await settle.mutateAsync({
                    groupId,
                    paidTo: toUser.userId,
                    amount: amountNum,
                    yearMonth: yearMonth ?? currentYearMonth(),
                    notes: notes.trim() || undefined
                })
                toast.success(t('settlement.settleSuccess'))
            }
            onOpenChange(false)
        } catch {
            toast.error(isEdit ? t('settlement.editFailed') : t('settlement.settleFailed'))
        } finally {
            setSubmitting(false)
        }
    }

    return (
        <Drawer open={open} onOpenChange={onOpenChange}>
            <DrawerContent className="flex flex-col border-t border-glass-border-strong bg-card">
                <DrawerHeader className="px-6 pt-6 pb-4">
                    <div className="flex items-center gap-3">
                        <span className="flex h-10 w-10 items-center justify-center rounded-full bg-brand-accent text-brand-primary">
                            {isEdit ? <Pencil className="h-5 w-5" /> : <HandCoins className="h-5 w-5" />}
                        </span>
                        <div className="flex-1 text-left">
                            <DrawerTitle className="text-lg font-semibold text-foreground">
                                {isEdit
                                    ? t('settlement.editDrawerTitle')
                                    : t('settlement.settleDrawerTitle')}
                            </DrawerTitle>
                            <DrawerDescription className="text-sm text-muted-foreground">
                                {isEdit
                                    ? t('settlement.editDrawerDesc')
                                    : t('settlement.settleDrawerDesc')}
                            </DrawerDescription>
                        </div>
                    </div>
                </DrawerHeader>

                <div className="space-y-5 px-6 pb-2">
                    <div className="space-y-2">
                        <label htmlFor="settle-amount" className="text-sm font-medium text-foreground">
                            {t('settlement.amount')}
                        </label>
                        <div className="relative">
                            <span className="absolute top-1/2 left-3 -translate-y-1/2 text-sm font-medium text-muted-foreground">
                                {currencySymbol}
                            </span>
                            <Input
                                id="settle-amount"
                                type="number"
                                inputMode="numeric"
                                value={amount}
                                onChange={(e) => setAmount(e.target.value)}
                                min="1"
                                step="1"
                                placeholder={t('settlement.amountPlaceholder')}
                                className="h-12 pl-12"
                            />
                        </div>
                    </div>

                    <div className="space-y-2">
                        <label htmlFor="settle-notes" className="text-sm font-medium text-foreground">
                            {t('settlement.notes')}{' '}
                            <span className="text-xs font-normal text-muted-foreground">
                                ({t('common.optional')})
                            </span>
                        </label>
                        <Input
                            id="settle-notes"
                            value={notes}
                            onChange={(e) => setNotes(e.target.value)}
                            placeholder={t('settlement.notesPlaceholder')}
                            className="h-12"
                        />
                    </div>
                </div>

                <DrawerFooter className="gap-2 px-6 pt-4 pb-6">
                    <Button
                        type="button"
                        onClick={handleConfirm}
                        disabled={!isValid || pending}
                        className="press-feedback h-12 w-full bg-brand-primary text-brand-primary-foreground hover:bg-brand-primary/90 disabled:opacity-50"
                    >
                        {pending
                            ? t('common.processing')
                            : isEdit
                                ? t('settlement.confirmEdit')
                                : t('settlement.confirmSettle')}
                    </Button>
                    <Button
                        type="button"
                        variant="ghost"
                        onClick={() => onOpenChange(false)}
                        disabled={pending}
                        className="h-12 w-full"
                    >
                        {t('common.cancel')}
                    </Button>
                </DrawerFooter>
            </DrawerContent>
        </Drawer>
    )
}

// src/features/settlement/components/SettlementDrawer.vue
<script setup lang="ts">
import { computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { HandCoins, Pencil } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { z } from 'zod'
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    DrawerFooter
} from '@/shared/components/ui/drawer'
import { Button } from '@/shared/components/ui/button'
import { Input } from '@/shared/components/ui/input'
import { Label } from '@/shared/components/ui/label'
import { useSettlementStore } from '@/features/settlement/stores/settlement'

const { t } = useI18n()
const settlementStore = useSettlementStore()

interface ToUser {
    userId: string
    displayName: string | null
}

interface Props {
    open: boolean
    groupId: string
    toUser: ToUser
    suggestedAmount: number
    yearMonth?: string | null
    editSettlementId?: string | null
    editNotes?: string | null
}

const props = withDefaults(defineProps<Props>(), {
    yearMonth: null,
    editSettlementId: null,
    editNotes: null
})

const emit = defineEmits<{
    'update:open': [value: boolean]
    settled: []
}>()

const isEditMode = computed(() => !!props.editSettlementId)

const settlementSchema = toTypedSchema(z.object({
    amount: z.number({
        required_error: t('validation.required'),
        invalid_type_error: t('validation.number')
    }).positive(t('settlement.invalidAmount')),
    notes: z.string()
}))

const settlementForm = useForm({
    validationSchema: settlementSchema,
    initialValues: {
        amount: undefined,
        notes: ''
    }
})

const submitting = computed(() => settlementForm.isSubmitting.value)
const amountError = computed(() => settlementForm.errors.value.amount ?? '')

const resetSettlementForm = () => {
    settlementForm.resetForm({
        values: {
            amount: props.suggestedAmount > 0
                ? props.suggestedAmount
                : undefined,
            notes: props.editNotes ?? ''
        }
    })
}

// Sync amount with suggestedAmount whenever the drawer opens
watch(
    () => props.open,
    (isOpen) => {
        if (isOpen) {
            resetSettlementForm()
        }
    }
)

const handleClose = () => {
    emit('update:open', false)
}

const submitSettlementForm = settlementForm.handleSubmit(async (values) => {
    try {
        if (isEditMode.value) {
            await settlementStore.updateSettlement(
                props.editSettlementId!,
                props.groupId,
                values.amount,
                values.notes.trim() || undefined
            )
            toast.success(t('settlement.editSuccess'))
        } else if (props.yearMonth) {
            await settlementStore.settleMonthlyDebt(
                props.groupId,
                props.toUser.userId,
                values.amount,
                props.yearMonth,
                values.notes.trim() || undefined
            )
            toast.success(t('settlement.settleSuccess'))
        } else {
            await settlementStore.createSettlement(
                props.groupId,
                props.toUser.userId,
                values.amount,
                values.notes.trim() || undefined
            )
            toast.success(t('settlement.settleSuccess'))
        }

        emit('settled')
        emit('update:open', false)
    } catch {
        toast.error(isEditMode.value
            ? t('settlement.editFailed')
            : t('settlement.settleFailed')
        )
    }
})
</script>

<template>
    <Drawer :open="props.open" @update:open="emit('update:open', $event)">
        <DrawerContent>
            <DrawerHeader class="px-6 pt-6 pb-4">
                <div class="flex items-center gap-3 mb-1">
                    <div class="flex h-10 w-10 items-center justify-center rounded-full bg-brand-accent">
                        <Pencil v-if="isEditMode" class="h-5 w-5 text-brand-primary" />
                        <HandCoins v-else class="h-5 w-5 text-brand-primary" />
                    </div>
                    <div class="flex-1 text-left">
                        <DrawerTitle class="text-lg font-semibold">
                            {{ isEditMode
                                ? t('settlement.editDrawerTitle')
                                : t('settlement.settleDrawerTitle')
                            }}
                        </DrawerTitle>
                        <DrawerDescription class="text-sm text-muted-foreground">
                            {{ isEditMode
                                ? t('settlement.editDrawerDesc')
                                : t('settlement.settleDrawerDesc', {
                                    name: props.toUser.displayName || t('common.unknown')
                                })
                            }}
                        </DrawerDescription>
                    </div>
                </div>
            </DrawerHeader>

            <div class="px-6 pb-2 space-y-5">
                <form class="space-y-5" @submit="submitSettlementForm">
                    <div class="space-y-2">
                        <Label for="settle-amount" class="text-sm font-medium">
                            {{ t('settlement.amount') }}
                        </Label>
                        <div class="relative">
                            <span class="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground font-medium">
                                NT$
                            </span>
                            <Input
                                id="settle-amount"
                                :model-value="settlementForm.values.amount ?? ''"
                                type="number"
                                min="0"
                                step="1"
                                class="pl-12 text-base h-12"
                                :class="amountError ? 'border-destructive' : ''"
                                :placeholder="t('settlement.amountPlaceholder')"
                                @update:model-value="settlementForm.setFieldValue('amount', $event === '' ? undefined : Number($event))"
                            />
                        </div>
                        <p v-if="amountError" class="text-xs text-destructive">
                            {{ amountError }}
                        </p>
                    </div>

                    <div class="space-y-2">
                        <Label for="settle-notes" class="text-sm font-medium">
                            {{ t('settlement.notes') }}
                            <span class="text-muted-foreground font-normal ml-1">
                                {{ t('common.optional') }}
                            </span>
                        </Label>
                        <textarea
                            id="settle-notes"
                            :value="settlementForm.values.notes"
                            rows="3"
                            class="w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 resize-none"
                            :placeholder="t('settlement.notesPlaceholder')"
                            @input="settlementForm.setFieldValue('notes', ($event.target as HTMLTextAreaElement).value)"
                        />
                    </div>

                    <DrawerFooter class="px-0 pb-4 pt-4 flex flex-col gap-2">
                        <Button
                            type="submit"
                            class="w-full h-12 bg-brand-primary hover:bg-brand-primary/90 text-brand-primary-foreground text-base font-medium"
                            :disabled="submitting"
                        >
                            <span v-if="submitting">{{ t('common.processing') }}</span>
                            <span v-else>
                                {{ isEditMode
                                    ? t('settlement.confirmEdit')
                                    : t('settlement.confirmSettle')
                                }}
                            </span>
                        </Button>
                        <Button
                            type="button"
                            variant="ghost"
                            class="w-full h-12 text-base"
                            :disabled="submitting"
                            @click="handleClose"
                        >
                            {{ t('common.cancel') }}
                        </Button>
                    </DrawerFooter>
                </form>
            </div>
        </DrawerContent>
    </Drawer>
</template>
