// src/pages/expense-detail/ExpenseDetailPage.vue
<script setup lang="ts">
import { computed, onMounted, ref, shallowRef, watch } from 'vue'
import { useDebounceFn } from '@vueuse/core'
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { z } from 'zod'
import { useRouter, useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Pencil, Trash2, User, Calendar, DollarSign, Loader2 } from 'lucide-vue-next'
import TopBar from '@/shared/components/TopBar.vue'
import { Button } from '@/shared/components/ui/button'
import { Badge } from '@/shared/components/ui/badge'
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger
} from '@/shared/components/ui/alert-dialog'
import {
    Avatar,
    AvatarFallback,
    AvatarImage
} from '@/shared/components/ui/avatar'
import {
    Dialog,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogScrollContent,
    DialogTitle
} from '@/shared/components/ui/dialog'
import { Input } from '@/shared/components/ui/input'
import { Label } from '@/shared/components/ui/label'
import { Calendar as CalendarComponent } from '@/shared/components/ui/calendar'
import { Popover, PopoverContent, PopoverTrigger } from '@/shared/components/ui/popover'
import { parseDate, type DateValue } from '@internationalized/date'
import SplitBadge from '@/features/split/components/SplitBadge.vue'
import SplitConfigurator from '@/features/split/components/SplitConfigurator.vue'
import { useExpenseStore } from '@/shared/stores'
import { useSplitStore } from '@/shared/stores'
import { useGroupStore } from '@/features/group/stores/group'
import { useCategories, CategoryUtils, type CategoryId } from '@/features/expense/composables/useCategories'
import type { SplitMethod } from '@/entities/split/types'
import type { SplitParticipant } from '@/entities/split/types'
import { supabase } from '@/shared/lib/supabase'
import { toast } from 'vue-sonner'

const router = useRouter()
const route = useRoute()
const { t } = useI18n()
const { categories } = useCategories()

const expenseId = route.params.id as string
const expenseStore = useExpenseStore()
const splitStore = useSplitStore()
const groupStore = useGroupStore()

// 從已載入的 expenses 中找到這筆
const expense = computed(() =>
    expenseStore.expenses.find(e => e.id === expenseId) ?? null
)

// 分帳資料
const splits = computed(() => splitStore.getSplitsForExpense(expenseId))

type SplitProfileMap = Record<string, { displayName: string | null; avatarUrl: string | null }>

const splitProfiles = ref<SplitProfileMap>({})

const detailedSplits = computed(() =>
    splits.value.map(split => ({
        ...split,
        displayName: splitProfiles.value[split.user_id]?.displayName ?? null,
        avatarUrl: splitProfiles.value[split.user_id]?.avatarUrl ?? null
    }))
)

// 圖標元件
const iconComponent = computed(() => {
    if (!expense.value) return null
    return CategoryUtils.getIconByKey(CategoryUtils.getIconKey(expense.value.category))
})

// 格式化金額
const formattedAmount = computed(() => {
    if (!expense.value) return ''
    return `NT$ ${Math.round(expense.value.amount).toLocaleString()}`
})

// 格式化日期
const formattedDate = computed(() => {
    if (!expense.value) return ''
    return expense.value.date.replace(/-/g, '/')
})

// 編輯 Dialog 狀態
const isEditDialogOpen = shallowRef(false)
const editDateValue = shallowRef<DateValue | undefined>(undefined)
const editSplitConfiguratorKey = ref(0)
const editSplitConfiguratorRef = ref<InstanceType<typeof SplitConfigurator> | null>(null)

const editExpenseSchema = computed(() => z.object({
    title: z.string()
        .trim()
        .min(1, t('validation.required')),
    amount: z.number({
        required_error: t('validation.required'),
        invalid_type_error: t('validation.number')
    }).positive(t('validation.positiveNumber')),
    category: z.string()
        .trim()
        .min(1, t('validation.required')),
    date: z.string()
        .trim()
        .min(1, t('validation.required'))
}))

const {
    values: editForm,
    errors: editErrors,
    defineField: defineEditField,
    handleSubmit: handleEditSubmit,
    resetForm: resetEditForm,
    setFieldValue: setEditFieldValue
} = useForm({
    validationSchema: computed(() => toTypedSchema(editExpenseSchema.value)),
    initialValues: {
        title: '',
        amount: undefined,
        category: 'food',
        date: ''
    }
})

const [editTitle, editTitleAttrs] = defineEditField('title')

const editSplitData = ref<{
    splitMethod: SplitMethod
    paidBy: string
    participants: SplitParticipant[]
}>({
    splitMethod: 'equal',
    paidBy: '',
    participants: []
})

const buildEditParticipants = (): SplitParticipant[] => {
    if (!expense.value?.group_id) return []

    const members = groupStore.membersByGroup[expense.value.group_id] ?? []
    const splitMap = new Map(splits.value.map(split => [split.user_id, split]))
    const participantIds = members.length > 0
        ? members.map(member => member.user_id)
        : Array.from(splitMap.keys())

    return participantIds.map(userId => {
        const split = splitMap.get(userId)

        return {
            userId,
            displayName: null,
            avatarUrl: null,
            amount: split?.amount ?? 0,
            percentage: split?.percentage ?? undefined,
            shares: split?.shares ?? undefined,
            isIncluded: split !== undefined || splits.value.length === 0
        }
    })
}

const openEditDialog = () => {
    if (!expense.value) return
    resetEditForm({
        values: {
            title: expense.value.title,
            amount: expense.value.amount,
            category: expense.value.category,
            date: expense.value.date.replace(/-/g, '/')
        }
    })
    const dateParts = expense.value.date.split('-')
    editDateValue.value = parseDate(`${dateParts[0]}-${dateParts[1]}-${dateParts[2]}`)

    if (expense.value.group_id) {
        editSplitData.value = {
            splitMethod: (expense.value.split_method ?? 'equal') as SplitMethod,
            paidBy: expense.value.paid_by ?? expense.value.user_id,
            participants: buildEditParticipants()
        }
        editSplitConfiguratorKey.value += 1
    }

    isEditDialogOpen.value = true
}

const handleEditDateSelect = (date: DateValue | undefined) => {
    if (date) {
        setEditFieldValue(
            'date',
            `${date.year}/${String(date.month).padStart(2, '0')}/${String(date.day).padStart(2, '0')}`
        )
    }
}

const formatEditDate = (dateStr: string) => {
    if (!dateStr) return t('home.selectDate')
    return dateStr
}

const saveEditExpense = handleEditSubmit(async (validatedValues) => {
    if (!expense.value) return
    try {
        const storeDate = validatedValues.date.replace(/\//g, '-')
        const updates = {
            title: validatedValues.title,
            amount: Math.round(validatedValues.amount),
            category: validatedValues.category as CategoryId,
            date: storeDate
        }

        if (expense.value.group_id) {
            if (!(editSplitConfiguratorRef.value?.isBalanced ?? false)) {
                toast.error(t('split.notBalanced'))
                return
            }

            const calculatedSplits = editSplitConfiguratorRef.value?.calculatedSplits ?? []
            const splitPayload = calculatedSplits
                .filter(participant => participant.isIncluded)
                .map(participant => ({
                    userId: participant.userId,
                    amount: participant.amount,
                    percentage: participant.percentage,
                    shares: participant.shares
                }))

            await expenseStore.updateExpense(expense.value.id, {
                ...updates,
                split_method: editSplitData.value.splitMethod,
                paid_by: editSplitData.value.paidBy,
                is_settled: false
            })

            await splitStore.updateExpenseSplits(expense.value.id, splitPayload)
        } else {
            await expenseStore.updateExpense(expense.value.id, updates)
        }

        isEditDialogOpen.value = false
        toast.success(t('expense.updated'))
    } catch (err) {
        console.error('更新費用失敗:', err)
        toast.error(t('expense.updateFailed'))
    }
})

const cancelEditExpense = () => {
    isEditDialogOpen.value = false
}

// 刪除費用
const handleDelete = async () => {
    if (!expense.value) return
    const deletedExpense = { ...expense.value }
    const expenseTitle = deletedExpense.title

    try {
        await expenseStore.deleteExpense(deletedExpense.id)
        router.back()
        toast.success(`${t('expense.deleted')}「${expenseTitle}」`, {
            action: {
                label: t('common.undo'),
                onClick: async () => {
                    try {
                        await expenseStore.addExpense({
                            title: deletedExpense.title,
                            amount: deletedExpense.amount,
                            category: deletedExpense.category,
                            icon: deletedExpense.icon ?? CategoryUtils.getIconKey(deletedExpense.category),
                            date: deletedExpense.date,
                            group_id: deletedExpense.group_id
                        })
                        toast.success(t('expense.restored'))
                        await expenseStore.fetchExpenses()
                    } catch (err) {
                        console.error('復原失敗:', err)
                        toast.error(t('expense.restoreFailed'))
                    }
                }
            },
            duration: 5000
        })
    } catch (err) {
        console.error('刪除費用失敗:', err)
        toast.error(t('expense.deleteFailed'))
    }
}

// 取得使用者頭像 fallback 文字
const getAvatarFallback = (displayName: string | null | undefined) => {
    if (!displayName) return '?'
    return displayName.slice(0, 1).toUpperCase()
}

const loadSplitProfiles = async () => {
    const unresolvedIds = [...new Set(splits.value.map(split => split.user_id))]
        .filter(userId => !(userId in splitProfiles.value))

    if (unresolvedIds.length === 0) return

    const { data, error: profileError } = await supabase
        .from('user_profiles')
        .select('id, display_name, avatar_url')
        .in('id', unresolvedIds)

    if (profileError) {
        console.error('載入分帳成員資料失敗:', profileError)
        return
    }

    const nextProfiles: SplitProfileMap = {}

    for (const profile of data ?? []) {
        nextProfiles[profile.id] = {
            displayName: profile.display_name ?? null,
            avatarUrl: profile.avatar_url ?? null
        }
    }

    splitProfiles.value = {
        ...splitProfiles.value,
        ...nextProfiles
    }
}

// 載入分帳資料
onMounted(async () => {
    if (expense.value?.group_id) {
        await splitStore.fetchSplitsForExpense(expenseId)
    }
})

const debouncedLoadSplitProfiles = useDebounceFn(loadSplitProfiles, 300)

watch(splits, () => {
    void debouncedLoadSplitProfiles()
}, { immediate: true })
</script>

<template>
    <div class="min-h-screen bg-background glass-page-bg">
        <TopBar
            :title="t('expense.detail', '支出詳情')"
            :show-back-button="true"
            @back="router.back()"
        >
            <template #action>
                <Button
                    variant="ghost"
                    size="icon"
                    class="h-10 w-10 rounded-full"
                    @click="openEditDialog"
                >
                    <Pencil class="h-5 w-5" />
                </Button>
            </template>
        </TopBar>

        <main class="px-4 pb-28 pt-6 space-y-4">
            <!-- 載入中 -->
            <div v-if="!expense && expenseStore.loading" class="flex flex-col items-center justify-center py-20 gap-4">
                <Loader2 class="h-8 w-8 animate-spin text-brand-primary" />
                <p class="text-sm text-muted-foreground">{{ t('common.loading', '載入中...') }}</p>
            </div>

            <!-- 找不到 -->
            <div v-else-if="!expense" class="text-center py-12">
                <p class="text-muted-foreground">{{ t('expense.notFound', '找不到此支出記錄') }}</p>
            </div>

            <template v-else>
                <!-- 基本資訊 Card (Hero) -->
                <div
                    class="glass-elevated rounded-2xl p-5 space-y-4"
                    :style="{ background: `linear-gradient(135deg, var(--category-${expense.category}-bg), var(--card))` }"
                >
                    <!-- 分類圖標 + 標題 -->
                    <div class="flex items-center gap-3">
                        <div class="flex h-14 w-14 items-center justify-center rounded-xl bg-brand-accent">
                            <component
                                v-if="iconComponent"
                                :is="iconComponent"
                                class="h-7 w-7 text-brand-primary"
                            />
                        </div>
                        <div class="flex-1 min-w-0">
                            <h2 class="text-base font-medium text-card-foreground truncate">
                                {{ expense.title }}
                            </h2>
                            <p class="text-xs text-muted-foreground">{{ expense.category }}</p>
                        </div>
                        <SplitBadge v-if="expense.split_method" :method="expense.split_method" />
                    </div>

                    <!-- 金額 -->
                    <div class="flex items-center gap-2">
                        <DollarSign class="h-4 w-4 text-muted-foreground" />
                        <span class="text-4xl font-bold text-expense">{{ formattedAmount }}</span>
                        <Badge v-if="expense.is_settled" variant="secondary" class="text-[10px] text-green-600">
                            {{ t('expense.settled', '已結算') }}
                        </Badge>
                    </div>

                    <!-- 日期 + 付款人 pills -->
                    <div class="flex flex-wrap items-center gap-2">
                        <span class="inline-flex items-center gap-1.5 bg-muted/50 rounded-full px-3 py-1 text-sm text-muted-foreground">
                            <Calendar class="h-4 w-4" />
                            {{ formattedDate }}
                        </span>

                        <span
                            v-if="expense.group_id && expense.user"
                            class="inline-flex items-center gap-1.5 bg-muted/50 rounded-full px-3 py-1 text-sm text-muted-foreground"
                        >
                            <User class="h-4 w-4" />
                            {{ t('expense.paidBy', '付款人') }}：{{ expense.user.display_name || t('expense.unknownUser', '未知使用者') }}
                        </span>
                    </div>

                    <!-- 備註 -->
                    <div v-if="expense.notes" class="rounded-lg bg-muted/50 px-3 py-2">
                        <p class="text-xs text-muted-foreground leading-relaxed">{{ expense.notes }}</p>
                    </div>
                </div>

                <!-- 分帳明細 Section（僅群組支出） -->
                <div v-if="expense.group_id" class="glass rounded-2xl p-5 space-y-3">
                    <div class="flex items-center justify-between">
                        <h3 class="text-sm font-medium text-foreground">{{ t('split.detail', '分帳明細') }}</h3>
                        <SplitBadge v-if="expense.split_method" :method="expense.split_method" />
                    </div>

                    <!-- 分帳載入中 -->
                    <div v-if="splitStore.loading" class="text-center py-4">
                        <p class="text-xs text-muted-foreground">{{ t('common.loading', '載入中...') }}</p>
                    </div>

                    <!-- 無分帳資料 -->
                    <div v-else-if="detailedSplits.length === 0" class="text-center py-4">
                        <p class="text-xs text-muted-foreground">{{ t('split.noData', '無分帳資料') }}</p>
                    </div>

                    <!-- 參與者列表 -->
                    <ul v-else class="space-y-2">
                        <li
                            v-for="split in detailedSplits"
                            :key="split.id"
                            class="flex items-center justify-between gap-3"
                        >
                            <div class="flex items-center gap-2">
                                <Avatar class="h-7 w-7">
                                    <AvatarImage :src="split.avatarUrl || ''" :alt="split.displayName || t('expense.unknownUser', '未知使用者')" />
                                    <AvatarFallback class="text-[10px]">
                                        {{ getAvatarFallback(split.displayName) }}
                                    </AvatarFallback>
                                </Avatar>
                                <span class="text-xs text-foreground">{{ split.displayName || t('expense.unknownUser', '未知使用者') }}</span>
                            </div>
                            <div class="flex items-center gap-1.5">
                                <span
                                    v-if="split.percentage !== null"
                                    class="text-[10px] text-muted-foreground"
                                >
                                    {{ split.percentage }}%
                                </span>
                                <span
                                    v-if="split.shares !== null"
                                    class="text-[10px] text-muted-foreground"
                                >
                                    {{ split.shares }}份
                                </span>
                                <span class="text-xs font-medium text-expense">
                                    NT$ {{ Math.round(split.amount) }}
                                </span>
                                <Badge
                                    v-if="split.is_settled"
                                    variant="secondary"
                                    class="text-[9px] px-1 py-0 text-green-600"
                                >
                                    {{ t('expense.settled', '已結算') }}
                                </Badge>
                            </div>
                        </li>
                    </ul>
                </div>

                <!-- 操作區域 -->
                <div class="flex gap-3">
                    <Button
                        variant="outline"
                        class="flex-1 press-feedback"
                        @click="openEditDialog"
                    >
                        <Pencil class="h-4 w-4 mr-2" />
                        {{ t('common.edit', '編輯') }}
                    </Button>

                    <AlertDialog>
                        <AlertDialogTrigger as-child>
                            <Button variant="destructive" class="flex-1 press-feedback">
                                <Trash2 class="h-4 w-4 mr-2" />
                                {{ t('common.delete', '刪除') }}
                            </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                            <AlertDialogHeader>
                                <AlertDialogTitle>{{ t('expense.confirmDelete', '確認刪除') }}</AlertDialogTitle>
                                <AlertDialogDescription>
                                    {{ t('expense.confirmDeleteDesc', '確定要刪除這筆支出記錄嗎？此操作無法撤銷。') }}
                                </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                                <AlertDialogCancel>{{ t('common.cancel', '取消') }}</AlertDialogCancel>
                                <AlertDialogAction @click="handleDelete">
                                    {{ t('common.delete', '刪除') }}
                                </AlertDialogAction>
                            </AlertDialogFooter>
                        </AlertDialogContent>
                    </AlertDialog>
                </div>
            </template>
        </main>

        <!-- 編輯費用 Dialog -->
        <Dialog v-model:open="isEditDialogOpen">
            <DialogScrollContent class="sm:max-w-2xl max-h-[calc(100vh-2rem)] overflow-hidden p-0 gap-0">
                <DialogHeader class="px-6 pt-6 pb-4 border-b border-border">
                    <DialogTitle>{{ t('expense.edit') }}</DialogTitle>
                    <DialogDescription>{{ t('expense.editDesc') }}</DialogDescription>
                </DialogHeader>

                <div class="overflow-y-auto px-6 py-4 max-h-[calc(100vh-14rem)]">
                    <div class="space-y-4">
                    <!-- 費用標題 -->
                    <div class="space-y-2">
                        <Label for="detail-edit-title">{{ t('expense.title') }}</Label>
                        <Input
                            id="detail-edit-title"
                            v-model="editTitle"
                            v-bind="editTitleAttrs"
                            :placeholder="t('expense.titlePlaceholder')"
                            :aria-invalid="Boolean(editErrors.title)"
                        />
                        <p v-if="editErrors.title" class="text-xs text-destructive">
                            {{ editErrors.title }}
                        </p>
                    </div>

                    <!-- 金額 -->
                    <div class="space-y-2">
                        <Label for="detail-edit-amount">{{ t('expense.amount') }} (NT$)</Label>
                        <Input
                            id="detail-edit-amount"
                            :model-value="editForm.amount ?? ''"
                            type="number"
                            min="0"
                            step="1"
                            :aria-invalid="Boolean(editErrors.amount)"
                            @update:model-value="setEditFieldValue('amount', $event === '' ? undefined : Number($event))"
                        />
                        <p v-if="editErrors.amount" class="text-xs text-destructive">
                            {{ editErrors.amount }}
                        </p>
                    </div>

                    <!-- 類別選擇 -->
                    <div class="space-y-2">
                        <Label>{{ t('expense.category') }}</Label>
                        <div class="grid grid-cols-3 gap-2">
                            <button
                                v-for="category in categories"
                                :key="category.id"
                                type="button"
                                @click="setEditFieldValue('category', category.id)"
                                :class="[
                                    'flex flex-col items-center gap-1.5 p-2 rounded-lg border-2 transition-all duration-200',
                                    editForm.category === category.id
                                        ? 'border-brand-primary bg-brand-accent'
                                        : 'border-border bg-background hover:border-brand-primary/50'
                                ]"
                            >
                                <div :class="[
                                    'flex h-8 w-8 items-center justify-center rounded-lg',
                                    editForm.category === category.id ? 'bg-brand-primary' : 'bg-brand-accent'
                                ]">
                                    <component
                                        :is="category.icon"
                                        :class="[
                                            'h-4 w-4',
                                            editForm.category === category.id ? 'text-brand-primary-foreground' : 'text-brand-primary'
                                        ]"
                                    />
                                </div>
                                <span class="text-xs font-medium">{{ category.name }}</span>
                            </button>
                        </div>
                        <p v-if="editErrors.category" class="text-xs text-destructive">
                            {{ editErrors.category }}
                        </p>
                    </div>

                    <!-- 日期選擇 -->
                    <div class="space-y-2">
                        <Label>{{ t('expense.date') }}</Label>
                        <Popover>
                            <PopoverTrigger as-child>
                                <Button
                                    variant="outline"
                                    :class="[
                                        'w-full justify-start text-left font-normal',
                                        editErrors.date && 'border-destructive'
                                    ]"
                                    :aria-invalid="Boolean(editErrors.date)"
                                >
                                    <Calendar class="mr-2 h-4 w-4" />
                                    {{ formatEditDate(editForm.date ?? '') }}
                                </Button>
                            </PopoverTrigger>
                            <PopoverContent class="w-auto p-0" align="start">
                                <CalendarComponent
                                    :model-value="editDateValue as any"
                                    @update:model-value="handleEditDateSelect"
                                    initial-focus
                                />
                            </PopoverContent>
                        </Popover>
                        <p v-if="editErrors.date" class="text-xs text-destructive">
                            {{ editErrors.date }}
                        </p>
                    </div>

                    <div v-if="expense?.group_id" class="space-y-2">
                        <Label>{{ t('split.stepSplitConfig') }}</Label>
                        <div class="rounded-xl border border-border bg-background p-3">
                            <SplitConfigurator
                                :key="editSplitConfiguratorKey"
                                ref="editSplitConfiguratorRef"
                                :total-amount="editForm.amount ?? 0"
                                :group-id="expense.group_id"
                                v-model:paid-by="editSplitData.paidBy"
                                v-model:split-method="editSplitData.splitMethod"
                                v-model:participants="editSplitData.participants"
                            />
                        </div>
                    </div>
                    </div>
                </div>

                <DialogFooter class="flex-col sm:flex-row gap-2 border-t border-border bg-background px-6 py-4">
                    <Button variant="outline" @click="cancelEditExpense" class="flex-1">
                        {{ t('common.cancel') }}
                    </Button>
                    <Button
                        @click="saveEditExpense"
                        class="flex-1 bg-brand-primary hover:bg-brand-primary/90"
                        :disabled="expenseStore.loading"
                    >
                        {{ expenseStore.loading ? t('common.saving', '儲存中...') : t('common.save') }}
                    </Button>
                </DialogFooter>
            </DialogScrollContent>
        </Dialog>
    </div>
</template>

// src/pages/expense-detail/ExpenseDetailPage.tsx
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useRouter } from '@tanstack/react-router'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { Pencil, Trash2, User, Calendar, DollarSign, Loader2, HandCoins } from 'lucide-react'
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { SplitConfigurator } from '@/features/split/components/SplitConfigurator'
import { calcSplits } from '@/features/split/lib/calcSplits'
import { useExpenses } from '@/features/expense/api/useExpenses'
import { useExpenseSplits } from '@/features/expense/api/useExpenseSplits'
import { useUpdateExpense } from '@/features/expense/api/useUpdateExpense'
import type { UpdateExpenseInput } from '@/features/expense/api/useUpdateExpense'
import { useDeleteExpense } from '@/features/expense/api/useDeleteExpense'
import { useSettleExpense } from '@/features/settlement/api/mutations'
import { useGroups } from '@/features/group/api/useGroups'
import { loadProfiles } from '@/features/group/api/profiles'
import { useAuthStore } from '@/features/auth/authStore'
import { CategoryUtils, categoryIds } from '@/features/expense/lib/categories'
import { formatCurrency } from '@/shared/lib/money'
import { queryKeys } from '@/shared/lib/queryKeys'
import { cn } from '@/shared/lib/utils'
import type { CategoryId } from '@/entities/expense/types'
import type { SplitParticipant } from '@/entities/split/types'
import type { SplitMethod } from '@/shared/lib/database.types'

// 支出詳情（Phase 5.1，對照 Vue ExpenseDetailPage.vue）。
//   顯示：從 useExpenses 找該筆 + useExpenseSplits 顯示分帳明細（僅群組費用）。
//   編輯：群組費用走 useUpdateExpense 原子 RPC（複用 SplitConfigurator 編輯 splits）；個人費用裸表 update。
//   單筆結清：useSettleExpense（群組且未結算時）。
//   刪除 + 完整 undo：useDeleteExpense 的 remove→snapshot→undo，以 sonner action toast 提供復原。
// 金額全走 formatCurrency + 該費用所屬群組幣別。

export default function ExpenseDetailPage({ id }: { id: string }) {
    const { t } = useTranslation()
    const router = useRouter()
    const client = useQueryClient()
    const currentUserId = useAuthStore((s) => s.user?.id ?? null)

    const { data: expensesData, isLoading } = useExpenses()
    const expense = useMemo(
        () => (expensesData ?? []).find((e) => e.id === id) ?? null,
        [expensesData, id]
    )

    const isGroup = !!expense?.group_id
    const { data: groupsData } = useGroups()
    const groupDetails = expense?.group_id
        ? groupsData?.find((g) => g.group.id === expense.group_id) ?? null
        : null
    const currency = groupDetails?.settings?.currency ?? 'TWD'
    const members = groupDetails?.members ?? []

    const {
        data: splitsData,
        isLoading: splitsLoading,
        isError: splitsError,
        isSuccess: splitsLoaded
    } = useExpenseSplits(isGroup ? id : null)
    const splits = useMemo(() => splitsData ?? [], [splitsData])
    const groupMembersReady = !isGroup || splits.length > 0 || members.length > 0
    const groupSplitsReady = !isGroup || (splitsLoaded && groupMembersReady)

    // 分帳成員名稱（reuse Phase 4 profiles.ts；union 成員 + split user 以覆蓋編輯與明細）。
    const profileIds = useMemo(
        () => [...new Set([...members.map((m) => m.user_id), ...splits.map((s) => s.user_id)])],
        [members, splits]
    )
    const profileIdsKey = useMemo(() => [...profileIds].sort().join(','), [profileIds])
    const { data: profileMap } = useQuery({
        queryKey: queryKeys.detailProfiles(profileIdsKey),
        queryFn: () => loadProfiles(client, profileIds),
        enabled: profileIds.length > 0
    })
    const resolveName = (userId: string): string => {
        if (userId === currentUserId) return t('common.me')
        return profileMap?.get(userId)?.display_name || t('expense.unknownUser')
    }

    // ── 編輯狀態 ───────────────────────────────────────────────
    const [editOpen, setEditOpen] = useState(false)
    const [editTitle, setEditTitle] = useState('')
    const [editAmount, setEditAmount] = useState<number | undefined>(undefined)
    const [editCategory, setEditCategory] = useState<CategoryId>('food')
    const [editDate, setEditDate] = useState('')
    const [splitMethod, setSplitMethod] = useState<SplitMethod>('equal')
    const [paidBy, setPaidBy] = useState('')
    const [participants, setParticipants] = useState<SplitParticipant[]>([])

    const [deleteOpen, setDeleteOpen] = useState(false)
    const [settleOpen, setSettleOpen] = useState(false)

    const updateExpense = useUpdateExpense()
    const settleExpense = useSettleExpense()
    const { remove, undo } = useDeleteExpense()

    const editCalc = useMemo(
        () => calcSplits(splitMethod, editAmount ?? 0, participants),
        [splitMethod, editAmount, participants]
    )

    const buildEditParticipants = (): SplitParticipant[] => {
        const splitMap = new Map(splits.map((s) => [s.user_id, s]))
        const ids = [...new Set([...members.map((m) => m.user_id), ...splitMap.keys()])]
        return ids.map((userId) => {
            const s = splitMap.get(userId)
            return {
                userId,
                displayName: null,
                avatarUrl: null,
                amount: s?.amount ?? 0,
                percentage: s?.percentage ?? undefined,
                shares: s?.shares ?? undefined,
                isIncluded: s !== undefined || splits.length === 0
            }
        })
    }

    const openEdit = () => {
        if (!expense) return
        if (expense.group_id && !groupSplitsReady) return
        setEditTitle(expense.title)
        setEditAmount(expense.amount)
        setEditCategory(expense.category as CategoryId)
        setEditDate(expense.date)
        if (expense.group_id) {
            setSplitMethod((expense.split_method ?? 'equal') as SplitMethod)
            setPaidBy(expense.paid_by ?? expense.user_id)
            setParticipants(buildEditParticipants())
        }
        setEditOpen(true)
    }

    const editValid =
        editTitle.trim().length > 0 &&
        editAmount !== undefined &&
        Number.isInteger(editAmount) &&
        editAmount > 0 &&
        editDate.length > 0 &&
        groupSplitsReady

    const saveEdit = async () => {
        if (!expense || !editValid || updateExpense.isPending) return
        const updates: UpdateExpenseInput = {
            title: editTitle.trim(),
            amount: editAmount as number,
            category: editCategory,
            date: editDate
        }
        try {
            if (expense.group_id) {
                if (!editCalc.isBalanced) {
                    toast.error(t('split.notBalanced'))
                    return
                }
                const included = participants.filter((p) => p.isIncluded)
                const splitPayload = included.map((p, i) => ({
                    userId: p.userId,
                    amount: editCalc.amounts[i] ?? 0,
                    percentage: splitMethod === 'percentage' ? p.percentage : undefined,
                    shares: splitMethod === 'shares' ? p.shares : undefined
                }))
                await updateExpense.mutateAsync({
                    id,
                    groupId: expense.group_id,
                    updates: { ...updates, split_method: splitMethod, paid_by: paidBy, is_settled: false },
                    splits: splitPayload
                })
            } else {
                await updateExpense.mutateAsync({ id, groupId: null, updates })
            }
            setEditOpen(false)
            toast.success(t('expense.updated'))
        } catch {
            toast.error(t('expense.updateFailed'))
        }
    }

    const handleDelete = async () => {
        if (!expense) return
        setDeleteOpen(false)
        const title = expense.title
        try {
            const snapshot = await remove.mutateAsync({ expenseId: id, groupId: expense.group_id })
            router.history.back()
            toast.success(`${t('expense.deleted')}「${title}」`, {
                action: {
                    label: t('common.undo'),
                    onClick: () => {
                        void undo
                            .mutateAsync(snapshot)
                            .then(() => toast.success(t('expense.restored')))
                            .catch(() => toast.error(t('expense.restoreFailed')))
                    }
                },
                duration: 5000
            })
        } catch {
            toast.error(t('expense.deleteFailed'))
        }
    }

    const handleSettle = async () => {
        if (!expense?.group_id) return
        setSettleOpen(false)
        try {
            const count = await settleExpense.mutateAsync({ expenseId: id, groupId: expense.group_id })
            toast.success(t('settlement.expenseSettleSuccess', { count }))
        } catch {
            toast.error(t('settlement.expenseSettleFailed'))
        }
    }

    // ── 載入 / 找不到 ──────────────────────────────────────────
    if (!expense && isLoading) {
        return (
            <main className="flex flex-col items-center justify-center gap-4 px-4 py-20">
                <Loader2 className="h-8 w-8 animate-spin text-brand-primary" />
                <p className="text-sm text-muted-foreground">{t('common.loading')}</p>
            </main>
        )
    }

    if (!expense) {
        return (
            <main className="px-4 py-12 text-center">
                <p className="text-muted-foreground">{t('expense.notFound')}</p>
            </main>
        )
    }

    const HeroIcon = CategoryUtils.getIconByCategory(expense.category)
    const canSettle = isGroup && !expense.is_settled

    return (
        <main className="space-y-4 px-4 pt-6 pb-28">
            {/* 基本資訊 Hero */}
            <div
                className="glass-elevated space-y-4 rounded-2xl p-5"
                style={{
                    background: `linear-gradient(135deg, var(--category-${expense.category}-bg), var(--card))`
                }}
            >
                <div className="flex items-center gap-3">
                    <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-brand-accent">
                        <HeroIcon className="h-7 w-7 text-brand-primary" />
                    </div>
                    <div className="min-w-0 flex-1">
                        <h2 className="truncate text-base font-medium text-card-foreground">{expense.title}</h2>
                        <p className="text-xs text-muted-foreground">{t(`expense.categories.${expense.category}`)}</p>
                    </div>
                    {expense.split_method && (
                        <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-medium text-muted-foreground">
                            {t(`split.methods.${expense.split_method}`)}
                        </span>
                    )}
                </div>

                <div className="flex items-center gap-2">
                    <DollarSign className="h-4 w-4 text-muted-foreground" />
                    <span className="text-4xl font-bold text-expense">
                        {formatCurrency(expense.amount, currency)}
                    </span>
                    {expense.is_settled && (
                        <span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-green-600">
                            {t('expense.settled')}
                        </span>
                    )}
                </div>

                <div className="flex flex-wrap items-center gap-2">
                    <span className="inline-flex items-center gap-1.5 rounded-full bg-muted/50 px-3 py-1 text-sm text-muted-foreground">
                        <Calendar className="h-4 w-4" />
                        {expense.date.replace(/-/g, '/')}
                    </span>
                    {isGroup && expense.user && (
                        <span className="inline-flex items-center gap-1.5 rounded-full bg-muted/50 px-3 py-1 text-sm text-muted-foreground">
                            <User className="h-4 w-4" />
                            {t('expense.paidBy')}: {expense.user.display_name || t('expense.unknownUser')}
                        </span>
                    )}
                </div>

                {expense.notes && (
                    <div className="rounded-lg bg-muted/50 px-3 py-2">
                        <p className="text-xs leading-relaxed text-muted-foreground">{expense.notes}</p>
                    </div>
                )}
            </div>

            {/* 分帳明細（僅群組） */}
            {isGroup && (
                <div className="glass space-y-3 rounded-2xl p-5">
                    <h3 className="text-sm font-medium text-foreground">{t('split.detail')}</h3>
                    {splitsLoading ? (
                        <p className="py-4 text-center text-xs text-muted-foreground">{t('common.loading')}</p>
                    ) : splitsError ? (
                        <p className="py-4 text-center text-xs text-destructive">{t('common.error')}</p>
                    ) : splitsLoaded && splits.length === 0 ? (
                        <p className="py-4 text-center text-xs text-muted-foreground">{t('split.noData')}</p>
                    ) : (
                        <ul className="space-y-2">
                            {splits.map((s) => (
                                <li key={s.id} className="flex items-center justify-between gap-3">
                                    <div className="flex items-center gap-2">
                                        <span className="flex h-7 w-7 items-center justify-center rounded-full bg-brand-accent text-[10px] text-brand-primary">
                                            {resolveName(s.user_id).charAt(0) || '?'}
                                        </span>
                                        <span className="text-xs text-foreground">{resolveName(s.user_id)}</span>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        {s.percentage !== null && (
                                            <span className="text-[10px] text-muted-foreground">{s.percentage}%</span>
                                        )}
                                        {s.shares !== null && (
                                            <span className="text-[10px] text-muted-foreground">×{s.shares}</span>
                                        )}
                                        <span className="text-xs font-medium text-expense">
                                            {formatCurrency(s.amount, currency)}
                                        </span>
                                        {s.is_settled && (
                                            <span className="rounded-full bg-muted px-1 py-0 text-[9px] text-green-600">
                                                {t('expense.settled')}
                                            </span>
                                        )}
                                    </div>
                                </li>
                            ))}
                        </ul>
                    )}
                </div>
            )}

            {/* 結清此筆 */}
            {canSettle && (
                <Button
                    className="press-feedback w-full bg-brand-primary text-brand-primary-foreground hover:bg-brand-primary/90"
                    disabled={settleExpense.isPending}
                    onClick={() => setSettleOpen(true)}
                >
                    <HandCoins className="mr-2 h-4 w-4" />
                    {settleExpense.isPending ? t('common.processing') : t('settlement.settleExpense')}
                </Button>
            )}

            {/* 編輯 / 刪除 */}
            <div className="flex gap-3">
                <Button
                    variant="outline"
                    className="press-feedback flex-1"
                    disabled={!groupSplitsReady}
                    onClick={openEdit}
                >
                    <Pencil className="mr-2 h-4 w-4" />
                    {t('common.edit')}
                </Button>
                <Button variant="destructive" className="press-feedback flex-1" onClick={() => setDeleteOpen(true)}>
                    <Trash2 className="mr-2 h-4 w-4" />
                    {t('common.delete')}
                </Button>
            </div>

            {/* 刪除確認 */}
            <Dialog open={deleteOpen} onOpenChange={setDeleteOpen}>
                <DialogContent className="bg-card sm:max-w-md">
                    <DialogHeader>
                        <DialogTitle>{t('expense.confirmDelete')}</DialogTitle>
                        <DialogDescription>{t('expense.confirmDeleteDesc')}</DialogDescription>
                    </DialogHeader>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setDeleteOpen(false)}>
                            {t('common.cancel')}
                        </Button>
                        <Button variant="destructive" onClick={handleDelete}>
                            {t('common.delete')}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* 結清確認 */}
            <Dialog open={settleOpen} onOpenChange={setSettleOpen}>
                <DialogContent className="bg-card sm:max-w-md">
                    <DialogHeader>
                        <DialogTitle>{t('settlement.expenseSettleConfirmTitle')}</DialogTitle>
                        <DialogDescription>{t('settlement.expenseSettleConfirmDesc')}</DialogDescription>
                    </DialogHeader>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setSettleOpen(false)}>
                            {t('common.cancel')}
                        </Button>
                        <Button onClick={handleSettle}>{t('settlement.confirmSettle')}</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>

            {/* 編輯 Dialog */}
            <Dialog open={editOpen} onOpenChange={setEditOpen}>
                <DialogContent className="max-h-[calc(100vh-2rem)] overflow-y-auto bg-card sm:max-w-2xl">
                    <DialogHeader>
                        <DialogTitle>{t('expense.edit')}</DialogTitle>
                        <DialogDescription>{t('expense.editDesc')}</DialogDescription>
                    </DialogHeader>

                    <div className="space-y-4">
                        <div className="space-y-2">
                            <Label htmlFor="detail-edit-title">{t('expense.title')}</Label>
                            <Input
                                id="detail-edit-title"
                                value={editTitle}
                                onChange={(e) => setEditTitle(e.target.value)}
                                placeholder={t('expense.titlePlaceholder')}
                            />
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="detail-edit-amount">{t('expense.amount')}</Label>
                            <Input
                                id="detail-edit-amount"
                                type="number"
                                inputMode="numeric"
                                min="0"
                                step="1"
                                value={editAmount ?? ''}
                                onChange={(e) =>
                                    setEditAmount(e.target.value === '' ? undefined : Number(e.target.value))
                                }
                            />
                        </div>

                        <div className="space-y-2">
                            <Label>{t('expense.category')}</Label>
                            <div className="grid grid-cols-3 gap-2">
                                {categoryIds.map((cid) => {
                                    const Icon = CategoryUtils.getIconByCategory(cid)
                                    const selected = editCategory === cid
                                    return (
                                        <button
                                            key={cid}
                                            type="button"
                                            onClick={() => setEditCategory(cid)}
                                            aria-pressed={selected}
                                            className={cn(
                                                'flex flex-col items-center gap-1.5 rounded-lg border-2 p-2 transition-all duration-200',
                                                selected
                                                    ? 'border-brand-primary bg-brand-accent'
                                                    : 'border-border bg-background hover:border-brand-primary/50'
                                            )}
                                        >
                                            <span
                                                className={cn(
                                                    'flex h-8 w-8 items-center justify-center rounded-lg',
                                                    selected ? 'bg-brand-primary' : 'bg-brand-accent'
                                                )}
                                            >
                                                <Icon
                                                    className={cn(
                                                        'h-4 w-4',
                                                        selected ? 'text-brand-primary-foreground' : 'text-brand-primary'
                                                    )}
                                                />
                                            </span>
                                            <span className="text-xs font-medium">{t(`expense.categories.${cid}`)}</span>
                                        </button>
                                    )
                                })}
                            </div>
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="detail-edit-date">{t('expense.date')}</Label>
                            <Input
                                id="detail-edit-date"
                                type="date"
                                value={editDate}
                                onChange={(e) => setEditDate(e.target.value)}
                            />
                        </div>

                        {isGroup && (
                            <div className="space-y-2">
                                <Label>{t('split.stepSplitConfig')}</Label>
                                <div className="rounded-xl border border-border bg-background p-3">
                                    <SplitConfigurator
                                        totalAmount={editAmount ?? 0}
                                        currency={currency}
                                        splitMethod={splitMethod}
                                        onSplitMethodChange={setSplitMethod}
                                        paidBy={paidBy}
                                        onPaidByChange={setPaidBy}
                                        participants={participants}
                                        onParticipantsChange={setParticipants}
                                        resolveName={resolveName}
                                    />
                                </div>
                            </div>
                        )}
                    </div>

                    <DialogFooter>
                        <Button variant="outline" className="flex-1" onClick={() => setEditOpen(false)}>
                            {t('common.cancel')}
                        </Button>
                        <Button
                            className="flex-1 bg-brand-primary hover:bg-brand-primary/90"
                            disabled={!editValid || updateExpense.isPending}
                            onClick={saveEdit}
                        >
                            {updateExpense.isPending ? t('common.saving') : t('common.save')}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </main>
    )
}
